// Code generated by ent, DO NOT EDIT.

package auditevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the auditevent type in the database.
	Label = "audit_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEventID holds the string denoting the event_id field in the database.
	FieldEventID = "event_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSubjectUser holds the string denoting the subject_user field in the database.
	FieldSubjectUser = "subject_user"
	// FieldSubjectCi holds the string denoting the subject_ci field in the database.
	FieldSubjectCi = "subject_ci"
	// FieldSubjectProxy holds the string denoting the subject_proxy field in the database.
	FieldSubjectProxy = "subject_proxy"
	// FieldOccurAt holds the string denoting the occur_at field in the database.
	FieldOccurAt = "occur_at"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// Table holds the table name of the auditevent in the database.
	Table = "audit_events"
)

// Columns holds all SQL columns for auditevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStatus,
	FieldTenantID,
	FieldEventID,
	FieldType,
	FieldSubjectUser,
	FieldSubjectCi,
	FieldSubjectProxy,
	FieldOccurAt,
	FieldMeta,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint64
)

// OrderOption defines the ordering options for the AuditEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEventID orders the results by the event_id field.
func ByEventID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// BySubjectUser orders the results by the subject_user field.
func BySubjectUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectUser, opts...).ToFunc()
}

// BySubjectCi orders the results by the subject_ci field.
func BySubjectCi(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectCi, opts...).ToFunc()
}

// BySubjectProxy orders the results by the subject_proxy field.
func BySubjectProxy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectProxy, opts...).ToFunc()
}

// ByOccurAt orders the results by the occur_at field.
func ByOccurAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurAt, opts...).ToFunc()
}
