// Code generated by ent, DO NOT EDIT.

package proxygroupmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxygroupmember type in the database.
	Label = "proxy_group_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDepartmentID holds the string denoting the department_id field in the database.
	FieldDepartmentID = "department_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldWorkerID holds the string denoting the worker_id field in the database.
	FieldWorkerID = "worker_id"
	// FieldWorkerGroupID holds the string denoting the worker_group_id field in the database.
	FieldWorkerGroupID = "worker_group_id"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// FieldLastSelectedAt holds the string denoting the last_selected_at field in the database.
	FieldLastSelectedAt = "last_selected_at"
	// FieldSelectCount holds the string denoting the select_count field in the database.
	FieldSelectCount = "select_count"
	// FieldIsBackup holds the string denoting the is_backup field in the database.
	FieldIsBackup = "is_backup"
	// FieldConsecutiveFailures holds the string denoting the consecutive_failures field in the database.
	FieldConsecutiveFailures = "consecutive_failures"
	// FieldLastFailureAt holds the string denoting the last_failure_at field in the database.
	FieldLastFailureAt = "last_failure_at"
	// EdgeProxy holds the string denoting the proxy edge name in mutations.
	EdgeProxy = "proxy"
	// EdgeProxyGroup holds the string denoting the proxy_group edge name in mutations.
	EdgeProxyGroup = "proxy_group"
	// Table holds the table name of the proxygroupmember in the database.
	Table = "ops_worker_group_members"
	// ProxyTable is the table that holds the proxy relation/edge.
	ProxyTable = "ops_worker_group_members"
	// ProxyInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxyInverseTable = "ops_workers"
	// ProxyColumn is the table column denoting the proxy relation/edge.
	ProxyColumn = "worker_id"
	// ProxyGroupTable is the table that holds the proxy_group relation/edge.
	ProxyGroupTable = "ops_worker_group_members"
	// ProxyGroupInverseTable is the table name for the ProxyGroup entity.
	// It exists in this package in order to avoid circular dependency with the "proxygroup" package.
	ProxyGroupInverseTable = "ops_worker_groups"
	// ProxyGroupColumn is the table column denoting the proxy_group relation/edge.
	ProxyGroupColumn = "worker_group_id"
)

// Columns holds all SQL columns for proxygroupmember fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldDepartmentID,
	FieldStatus,
	FieldWorkerID,
	FieldWorkerGroupID,
	FieldWeight,
	FieldPriority,
	FieldJoinedAt,
	FieldLastSelectedAt,
	FieldSelectCount,
	FieldIsBackup,
	FieldConsecutiveFailures,
	FieldLastFailureAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	WeightValidator func(int) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	PriorityValidator func(int) error
	// DefaultSelectCount holds the default value on creation for the "select_count" field.
	DefaultSelectCount int
	// DefaultIsBackup holds the default value on creation for the "is_backup" field.
	DefaultIsBackup bool
	// DefaultConsecutiveFailures holds the default value on creation for the "consecutive_failures" field.
	DefaultConsecutiveFailures int
)

// OrderOption defines the ordering options for the ProxyGroupMember queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDepartmentID orders the results by the department_id field.
func ByDepartmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartmentID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByWorkerID orders the results by the worker_id field.
func ByWorkerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerID, opts...).ToFunc()
}

// ByWorkerGroupID orders the results by the worker_group_id field.
func ByWorkerGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerGroupID, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}

// ByLastSelectedAt orders the results by the last_selected_at field.
func ByLastSelectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSelectedAt, opts...).ToFunc()
}

// BySelectCount orders the results by the select_count field.
func BySelectCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSelectCount, opts...).ToFunc()
}

// ByIsBackup orders the results by the is_backup field.
func ByIsBackup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsBackup, opts...).ToFunc()
}

// ByConsecutiveFailures orders the results by the consecutive_failures field.
func ByConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailures, opts...).ToFunc()
}

// ByLastFailureAt orders the results by the last_failure_at field.
func ByLastFailureAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastFailureAt, opts...).ToFunc()
}

// ByProxyField orders the results by proxy field.
func ByProxyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxyStep(), sql.OrderByField(field, opts...))
	}
}

// ByProxyGroupField orders the results by proxy_group field.
func ByProxyGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxyGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newProxyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
	)
}
func newProxyGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxyGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProxyGroupTable, ProxyGroupColumn),
	)
}
