// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/accessprofile"
)

// AccessProfileCreate is the builder for creating a AccessProfile entity.
type AccessProfileCreate struct {
	config
	mutation *AccessProfileMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccessProfileCreate) SetCreatedAt(v time.Time) *AccessProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccessProfileCreate) SetNillableCreatedAt(v *time.Time) *AccessProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccessProfileCreate) SetUpdatedAt(v time.Time) *AccessProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccessProfileCreate) SetNillableUpdatedAt(v *time.Time) *AccessProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AccessProfileCreate) SetStatus(v uint8) *AccessProfileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AccessProfileCreate) SetNillableStatus(v *uint8) *AccessProfileCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *AccessProfileCreate) SetTenantID(v uint64) *AccessProfileCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *AccessProfileCreate) SetNillableTenantID(v *uint64) *AccessProfileCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCiID sets the "ci_id" field.
func (_c *AccessProfileCreate) SetCiID(v string) *AccessProfileCreate {
	_c.mutation.SetCiID(v)
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *AccessProfileCreate) SetCapabilities(v []string) *AccessProfileCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetPorts sets the "ports" field.
func (_c *AccessProfileCreate) SetPorts(v map[string]int) *AccessProfileCreate {
	_c.mutation.SetPorts(v)
	return _c
}

// SetCredentialRef sets the "credential_ref" field.
func (_c *AccessProfileCreate) SetCredentialRef(v string) *AccessProfileCreate {
	_c.mutation.SetCredentialRef(v)
	return _c
}

// SetNillableCredentialRef sets the "credential_ref" field if the given value is not nil.
func (_c *AccessProfileCreate) SetNillableCredentialRef(v *string) *AccessProfileCreate {
	if v != nil {
		_c.SetCredentialRef(*v)
	}
	return _c
}

// SetPreferProxy sets the "prefer_proxy" field.
func (_c *AccessProfileCreate) SetPreferProxy(v string) *AccessProfileCreate {
	_c.mutation.SetPreferProxy(v)
	return _c
}

// SetNillablePreferProxy sets the "prefer_proxy" field if the given value is not nil.
func (_c *AccessProfileCreate) SetNillablePreferProxy(v *string) *AccessProfileCreate {
	if v != nil {
		_c.SetPreferProxy(*v)
	}
	return _c
}

// SetJumpChain sets the "jump_chain" field.
func (_c *AccessProfileCreate) SetJumpChain(v []string) *AccessProfileCreate {
	_c.mutation.SetJumpChain(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *AccessProfileCreate) SetTags(v map[string]string) *AccessProfileCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AccessProfileCreate) SetID(v uint64) *AccessProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AccessProfileMutation object of the builder.
func (_c *AccessProfileCreate) Mutation() *AccessProfileMutation {
	return _c.mutation
}

// Save creates the AccessProfile in the database.
func (_c *AccessProfileCreate) Save(ctx context.Context) (*AccessProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccessProfileCreate) SaveX(ctx context.Context) *AccessProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccessProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accessprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accessprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := accessprofile.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := accessprofile.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccessProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccessProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccessProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "AccessProfile.tenant_id"`)}
	}
	if _, ok := _c.mutation.CiID(); !ok {
		return &ValidationError{Name: "ci_id", err: errors.New(`ent: missing required field "AccessProfile.ci_id"`)}
	}
	return nil
}

func (_c *AccessProfileCreate) sqlSave(ctx context.Context) (*AccessProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccessProfileCreate) createSpec() (*AccessProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &AccessProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accessprofile.Table, sqlgraph.NewFieldSpec(accessprofile.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accessprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accessprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(accessprofile.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(accessprofile.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CiID(); ok {
		_spec.SetField(accessprofile.FieldCiID, field.TypeString, value)
		_node.CiID = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(accessprofile.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.Ports(); ok {
		_spec.SetField(accessprofile.FieldPorts, field.TypeJSON, value)
		_node.Ports = value
	}
	if value, ok := _c.mutation.CredentialRef(); ok {
		_spec.SetField(accessprofile.FieldCredentialRef, field.TypeString, value)
		_node.CredentialRef = value
	}
	if value, ok := _c.mutation.PreferProxy(); ok {
		_spec.SetField(accessprofile.FieldPreferProxy, field.TypeString, value)
		_node.PreferProxy = value
	}
	if value, ok := _c.mutation.JumpChain(); ok {
		_spec.SetField(accessprofile.FieldJumpChain, field.TypeJSON, value)
		_node.JumpChain = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(accessprofile.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	return _node, _spec
}

// AccessProfileCreateBulk is the builder for creating many AccessProfile entities in bulk.
type AccessProfileCreateBulk struct {
	config
	err      error
	builders []*AccessProfileCreate
}

// Save creates the AccessProfile entities in the database.
func (_c *AccessProfileCreateBulk) Save(ctx context.Context) ([]*AccessProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccessProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccessProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccessProfileCreateBulk) SaveX(ctx context.Context) []*AccessProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccessProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccessProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
