// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/agentgroup"
)

// AgentGroupCreate is the builder for creating a AgentGroup entity.
type AgentGroupCreate struct {
	config
	mutation *AgentGroupMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentGroupCreate) SetCreatedAt(v time.Time) *AgentGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableCreatedAt(v *time.Time) *AgentGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentGroupCreate) SetUpdatedAt(v time.Time) *AgentGroupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableUpdatedAt(v *time.Time) *AgentGroupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *AgentGroupCreate) SetTenantID(v uint64) *AgentGroupCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableTenantID(v *uint64) *AgentGroupCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentGroupCreate) SetStatus(v uint8) *AgentGroupCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableStatus(v *uint8) *AgentGroupCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AgentGroupCreate) SetName(v string) *AgentGroupCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AgentGroupCreate) SetDescription(v string) *AgentGroupCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableDescription(v *string) *AgentGroupCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSelectionStrategy sets the "selection_strategy" field.
func (_c *AgentGroupCreate) SetSelectionStrategy(v agentgroup.SelectionStrategy) *AgentGroupCreate {
	_c.mutation.SetSelectionStrategy(v)
	return _c
}

// SetNillableSelectionStrategy sets the "selection_strategy" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableSelectionStrategy(v *agentgroup.SelectionStrategy) *AgentGroupCreate {
	if v != nil {
		_c.SetSelectionStrategy(*v)
	}
	return _c
}

// SetHealthCheckInterval sets the "health_check_interval" field.
func (_c *AgentGroupCreate) SetHealthCheckInterval(v int) *AgentGroupCreate {
	_c.mutation.SetHealthCheckInterval(v)
	return _c
}

// SetNillableHealthCheckInterval sets the "health_check_interval" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableHealthCheckInterval(v *int) *AgentGroupCreate {
	if v != nil {
		_c.SetHealthCheckInterval(*v)
	}
	return _c
}

// SetAutoFailover sets the "auto_failover" field.
func (_c *AgentGroupCreate) SetAutoFailover(v bool) *AgentGroupCreate {
	_c.mutation.SetAutoFailover(v)
	return _c
}

// SetNillableAutoFailover sets the "auto_failover" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableAutoFailover(v *bool) *AgentGroupCreate {
	if v != nil {
		_c.SetAutoFailover(*v)
	}
	return _c
}

// SetMaxRetryCount sets the "max_retry_count" field.
func (_c *AgentGroupCreate) SetMaxRetryCount(v int) *AgentGroupCreate {
	_c.mutation.SetMaxRetryCount(v)
	return _c
}

// SetNillableMaxRetryCount sets the "max_retry_count" field if the given value is not nil.
func (_c *AgentGroupCreate) SetNillableMaxRetryCount(v *int) *AgentGroupCreate {
	if v != nil {
		_c.SetMaxRetryCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentGroupCreate) SetID(v uint64) *AgentGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AgentGroupMutation object of the builder.
func (_c *AgentGroupCreate) Mutation() *AgentGroupMutation {
	return _c.mutation
}

// Save creates the AgentGroup in the database.
func (_c *AgentGroupCreate) Save(ctx context.Context) (*AgentGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentGroupCreate) SaveX(ctx context.Context) *AgentGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agentgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agentgroup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := agentgroup.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := agentgroup.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SelectionStrategy(); !ok {
		v := agentgroup.DefaultSelectionStrategy
		_c.mutation.SetSelectionStrategy(v)
	}
	if _, ok := _c.mutation.HealthCheckInterval(); !ok {
		v := agentgroup.DefaultHealthCheckInterval
		_c.mutation.SetHealthCheckInterval(v)
	}
	if _, ok := _c.mutation.AutoFailover(); !ok {
		v := agentgroup.DefaultAutoFailover
		_c.mutation.SetAutoFailover(v)
	}
	if _, ok := _c.mutation.MaxRetryCount(); !ok {
		v := agentgroup.DefaultMaxRetryCount
		_c.mutation.SetMaxRetryCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentGroupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentGroup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentGroup.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "AgentGroup.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentGroup.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := agentgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentGroup.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := agentgroup.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentGroup.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SelectionStrategy(); !ok {
		return &ValidationError{Name: "selection_strategy", err: errors.New(`ent: missing required field "AgentGroup.selection_strategy"`)}
	}
	if v, ok := _c.mutation.SelectionStrategy(); ok {
		if err := agentgroup.SelectionStrategyValidator(v); err != nil {
			return &ValidationError{Name: "selection_strategy", err: fmt.Errorf(`ent: validator failed for field "AgentGroup.selection_strategy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HealthCheckInterval(); !ok {
		return &ValidationError{Name: "health_check_interval", err: errors.New(`ent: missing required field "AgentGroup.health_check_interval"`)}
	}
	if _, ok := _c.mutation.AutoFailover(); !ok {
		return &ValidationError{Name: "auto_failover", err: errors.New(`ent: missing required field "AgentGroup.auto_failover"`)}
	}
	if _, ok := _c.mutation.MaxRetryCount(); !ok {
		return &ValidationError{Name: "max_retry_count", err: errors.New(`ent: missing required field "AgentGroup.max_retry_count"`)}
	}
	return nil
}

func (_c *AgentGroupCreate) sqlSave(ctx context.Context) (*AgentGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentGroupCreate) createSpec() (*AgentGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentgroup.Table, sqlgraph.NewFieldSpec(agentgroup.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agentgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agentgroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(agentgroup.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agentgroup.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(agentgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(agentgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SelectionStrategy(); ok {
		_spec.SetField(agentgroup.FieldSelectionStrategy, field.TypeEnum, value)
		_node.SelectionStrategy = value
	}
	if value, ok := _c.mutation.HealthCheckInterval(); ok {
		_spec.SetField(agentgroup.FieldHealthCheckInterval, field.TypeInt, value)
		_node.HealthCheckInterval = value
	}
	if value, ok := _c.mutation.AutoFailover(); ok {
		_spec.SetField(agentgroup.FieldAutoFailover, field.TypeBool, value)
		_node.AutoFailover = value
	}
	if value, ok := _c.mutation.MaxRetryCount(); ok {
		_spec.SetField(agentgroup.FieldMaxRetryCount, field.TypeInt, value)
		_node.MaxRetryCount = value
	}
	return _node, _spec
}

// AgentGroupCreateBulk is the builder for creating many AgentGroup entities in bulk.
type AgentGroupCreateBulk struct {
	config
	err      error
	builders []*AgentGroupCreate
}

// Save creates the AgentGroup entities in the database.
func (_c *AgentGroupCreateBulk) Save(ctx context.Context) ([]*AgentGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentGroupCreateBulk) SaveX(ctx context.Context) []*AgentGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
