// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/agent"
	"github.com/coder-lulu/newbee-ops-rpc/ent/predicate"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdate) SetUpdatedAt(v time.Time) *AgentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdate) SetStatus(v uint8) *AgentUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableStatus(v *uint8) *AgentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AgentUpdate) AddStatus(v int8) *AgentUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *AgentUpdate) ClearStatus() *AgentUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdate) SetName(v string) *AgentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableName(v *string) *AgentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentUpdate) SetAgentID(v string) *AgentUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableAgentID(v *string) *AgentUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *AgentUpdate) SetHost(v string) *AgentUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableHost(v *string) *AgentUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *AgentUpdate) SetPort(v int) *AgentUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *AgentUpdate) SetNillablePort(v *int) *AgentUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *AgentUpdate) AddPort(v int) *AgentUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AgentUpdate) SetAPIKey(v string) *AgentUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableAPIKey(v *string) *AgentUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentUpdate) SetDescription(v string) *AgentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableDescription(v *string) *AgentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AgentUpdate) ClearDescription() *AgentUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetAgentStatus sets the "agent_status" field.
func (_u *AgentUpdate) SetAgentStatus(v agent.AgentStatus) *AgentUpdate {
	_u.mutation.SetAgentStatus(v)
	return _u
}

// SetNillableAgentStatus sets the "agent_status" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableAgentStatus(v *agent.AgentStatus) *AgentUpdate {
	if v != nil {
		_u.SetAgentStatus(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *AgentUpdate) SetLastHeartbeat(v time.Time) *AgentUpdate {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableLastHeartbeat(v *time.Time) *AgentUpdate {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *AgentUpdate) ClearLastHeartbeat() *AgentUpdate {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetHeartbeatInterval sets the "heartbeat_interval" field.
func (_u *AgentUpdate) SetHeartbeatInterval(v int) *AgentUpdate {
	_u.mutation.ResetHeartbeatInterval()
	_u.mutation.SetHeartbeatInterval(v)
	return _u
}

// SetNillableHeartbeatInterval sets the "heartbeat_interval" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableHeartbeatInterval(v *int) *AgentUpdate {
	if v != nil {
		_u.SetHeartbeatInterval(*v)
	}
	return _u
}

// AddHeartbeatInterval adds value to the "heartbeat_interval" field.
func (_u *AgentUpdate) AddHeartbeatInterval(v int) *AgentUpdate {
	_u.mutation.AddHeartbeatInterval(v)
	return _u
}

// SetLastOnlineAt sets the "last_online_at" field.
func (_u *AgentUpdate) SetLastOnlineAt(v time.Time) *AgentUpdate {
	_u.mutation.SetLastOnlineAt(v)
	return _u
}

// SetNillableLastOnlineAt sets the "last_online_at" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableLastOnlineAt(v *time.Time) *AgentUpdate {
	if v != nil {
		_u.SetLastOnlineAt(*v)
	}
	return _u
}

// ClearLastOnlineAt clears the value of the "last_online_at" field.
func (_u *AgentUpdate) ClearLastOnlineAt() *AgentUpdate {
	_u.mutation.ClearLastOnlineAt()
	return _u
}

// SetSupportedProviders sets the "supported_providers" field.
func (_u *AgentUpdate) SetSupportedProviders(v []string) *AgentUpdate {
	_u.mutation.SetSupportedProviders(v)
	return _u
}

// AppendSupportedProviders appends value to the "supported_providers" field.
func (_u *AgentUpdate) AppendSupportedProviders(v []string) *AgentUpdate {
	_u.mutation.AppendSupportedProviders(v)
	return _u
}

// ClearSupportedProviders clears the value of the "supported_providers" field.
func (_u *AgentUpdate) ClearSupportedProviders() *AgentUpdate {
	_u.mutation.ClearSupportedProviders()
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *AgentUpdate) SetCapabilities(v []string) *AgentUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *AgentUpdate) AppendCapabilities(v []string) *AgentUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// ClearCapabilities clears the value of the "capabilities" field.
func (_u *AgentUpdate) ClearCapabilities() *AgentUpdate {
	_u.mutation.ClearCapabilities()
	return _u
}

// SetMaxConcurrentTasks sets the "max_concurrent_tasks" field.
func (_u *AgentUpdate) SetMaxConcurrentTasks(v int) *AgentUpdate {
	_u.mutation.ResetMaxConcurrentTasks()
	_u.mutation.SetMaxConcurrentTasks(v)
	return _u
}

// SetNillableMaxConcurrentTasks sets the "max_concurrent_tasks" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableMaxConcurrentTasks(v *int) *AgentUpdate {
	if v != nil {
		_u.SetMaxConcurrentTasks(*v)
	}
	return _u
}

// AddMaxConcurrentTasks adds value to the "max_concurrent_tasks" field.
func (_u *AgentUpdate) AddMaxConcurrentTasks(v int) *AgentUpdate {
	_u.mutation.AddMaxConcurrentTasks(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *AgentUpdate) SetTags(v []string) *AgentUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *AgentUpdate) AppendTags(v []string) *AgentUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *AgentUpdate) ClearTags() *AgentUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetRegion sets the "region" field.
func (_u *AgentUpdate) SetRegion(v string) *AgentUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableRegion(v *string) *AgentUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *AgentUpdate) ClearRegion() *AgentUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// SetResourceLimits sets the "resource_limits" field.
func (_u *AgentUpdate) SetResourceLimits(v map[string]interface{}) *AgentUpdate {
	_u.mutation.SetResourceLimits(v)
	return _u
}

// ClearResourceLimits clears the value of the "resource_limits" field.
func (_u *AgentUpdate) ClearResourceLimits() *AgentUpdate {
	_u.mutation.ClearResourceLimits()
	return _u
}

// SetLocalIP sets the "local_ip" field.
func (_u *AgentUpdate) SetLocalIP(v string) *AgentUpdate {
	_u.mutation.SetLocalIP(v)
	return _u
}

// SetNillableLocalIP sets the "local_ip" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableLocalIP(v *string) *AgentUpdate {
	if v != nil {
		_u.SetLocalIP(*v)
	}
	return _u
}

// ClearLocalIP clears the value of the "local_ip" field.
func (_u *AgentUpdate) ClearLocalIP() *AgentUpdate {
	_u.mutation.ClearLocalIP()
	return _u
}

// SetPublicIP sets the "public_ip" field.
func (_u *AgentUpdate) SetPublicIP(v string) *AgentUpdate {
	_u.mutation.SetPublicIP(v)
	return _u
}

// SetNillablePublicIP sets the "public_ip" field if the given value is not nil.
func (_u *AgentUpdate) SetNillablePublicIP(v *string) *AgentUpdate {
	if v != nil {
		_u.SetPublicIP(*v)
	}
	return _u
}

// ClearPublicIP clears the value of the "public_ip" field.
func (_u *AgentUpdate) ClearPublicIP() *AgentUpdate {
	_u.mutation.ClearPublicIP()
	return _u
}

// SetNetworkSegments sets the "network_segments" field.
func (_u *AgentUpdate) SetNetworkSegments(v []string) *AgentUpdate {
	_u.mutation.SetNetworkSegments(v)
	return _u
}

// AppendNetworkSegments appends value to the "network_segments" field.
func (_u *AgentUpdate) AppendNetworkSegments(v []string) *AgentUpdate {
	_u.mutation.AppendNetworkSegments(v)
	return _u
}

// ClearNetworkSegments clears the value of the "network_segments" field.
func (_u *AgentUpdate) ClearNetworkSegments() *AgentUpdate {
	_u.mutation.ClearNetworkSegments()
	return _u
}

// SetActiveSessions sets the "active_sessions" field.
func (_u *AgentUpdate) SetActiveSessions(v int) *AgentUpdate {
	_u.mutation.ResetActiveSessions()
	_u.mutation.SetActiveSessions(v)
	return _u
}

// SetNillableActiveSessions sets the "active_sessions" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableActiveSessions(v *int) *AgentUpdate {
	if v != nil {
		_u.SetActiveSessions(*v)
	}
	return _u
}

// AddActiveSessions adds value to the "active_sessions" field.
func (_u *AgentUpdate) AddActiveSessions(v int) *AgentUpdate {
	_u.mutation.AddActiveSessions(v)
	return _u
}

// SetCPUUsage sets the "cpu_usage" field.
func (_u *AgentUpdate) SetCPUUsage(v float64) *AgentUpdate {
	_u.mutation.ResetCPUUsage()
	_u.mutation.SetCPUUsage(v)
	return _u
}

// SetNillableCPUUsage sets the "cpu_usage" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableCPUUsage(v *float64) *AgentUpdate {
	if v != nil {
		_u.SetCPUUsage(*v)
	}
	return _u
}

// AddCPUUsage adds value to the "cpu_usage" field.
func (_u *AgentUpdate) AddCPUUsage(v float64) *AgentUpdate {
	_u.mutation.AddCPUUsage(v)
	return _u
}

// SetMemoryUsage sets the "memory_usage" field.
func (_u *AgentUpdate) SetMemoryUsage(v float64) *AgentUpdate {
	_u.mutation.ResetMemoryUsage()
	_u.mutation.SetMemoryUsage(v)
	return _u
}

// SetNillableMemoryUsage sets the "memory_usage" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableMemoryUsage(v *float64) *AgentUpdate {
	if v != nil {
		_u.SetMemoryUsage(*v)
	}
	return _u
}

// AddMemoryUsage adds value to the "memory_usage" field.
func (_u *AgentUpdate) AddMemoryUsage(v float64) *AgentUpdate {
	_u.mutation.AddMemoryUsage(v)
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *AgentUpdate) SetTotalRequests(v int64) *AgentUpdate {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableTotalRequests(v *int64) *AgentUpdate {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *AgentUpdate) AddTotalRequests(v int64) *AgentUpdate {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetSuccessfulRequests sets the "successful_requests" field.
func (_u *AgentUpdate) SetSuccessfulRequests(v int64) *AgentUpdate {
	_u.mutation.ResetSuccessfulRequests()
	_u.mutation.SetSuccessfulRequests(v)
	return _u
}

// SetNillableSuccessfulRequests sets the "successful_requests" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableSuccessfulRequests(v *int64) *AgentUpdate {
	if v != nil {
		_u.SetSuccessfulRequests(*v)
	}
	return _u
}

// AddSuccessfulRequests adds value to the "successful_requests" field.
func (_u *AgentUpdate) AddSuccessfulRequests(v int64) *AgentUpdate {
	_u.mutation.AddSuccessfulRequests(v)
	return _u
}

// SetFailedRequests sets the "failed_requests" field.
func (_u *AgentUpdate) SetFailedRequests(v int64) *AgentUpdate {
	_u.mutation.ResetFailedRequests()
	_u.mutation.SetFailedRequests(v)
	return _u
}

// SetNillableFailedRequests sets the "failed_requests" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableFailedRequests(v *int64) *AgentUpdate {
	if v != nil {
		_u.SetFailedRequests(*v)
	}
	return _u
}

// AddFailedRequests adds value to the "failed_requests" field.
func (_u *AgentUpdate) AddFailedRequests(v int64) *AgentUpdate {
	_u.mutation.AddFailedRequests(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentUpdate) SetVersion(v string) *AgentUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableVersion(v *string) *AgentUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *AgentUpdate) ClearVersion() *AgentUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentUpdate) SetMetadata(v map[string]interface{}) *AgentUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AgentUpdate) ClearMetadata() *AgentUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AgentUpdate) SetLastError(v string) *AgentUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableLastError(v *string) *AgentUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AgentUpdate) ClearLastError() *AgentUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AgentID(); ok {
		if err := agent.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "Agent.agent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := agent.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Agent.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := agent.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "Agent.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := agent.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Agent.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AgentStatus(); ok {
		if err := agent.AgentStatusValidator(v); err != nil {
			return &ValidationError{Name: "agent_status", err: fmt.Errorf(`ent: validator failed for field "Agent.agent_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := agent.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Agent.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalIP(); ok {
		if err := agent.LocalIPValidator(v); err != nil {
			return &ValidationError{Name: "local_ip", err: fmt.Errorf(`ent: validator failed for field "Agent.local_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicIP(); ok {
		if err := agent.PublicIPValidator(v); err != nil {
			return &ValidationError{Name: "public_ip", err: fmt.Errorf(`ent: validator failed for field "Agent.public_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := agent.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Agent.version": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(agent.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(agent.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(agent.FieldAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(agent.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(agent.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(agent.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(agent.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AgentStatus(); ok {
		_spec.SetField(agent.FieldAgentStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(agent.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(agent.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatInterval(); ok {
		_spec.SetField(agent.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeartbeatInterval(); ok {
		_spec.AddField(agent.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastOnlineAt(); ok {
		_spec.SetField(agent.FieldLastOnlineAt, field.TypeTime, value)
	}
	if _u.mutation.LastOnlineAtCleared() {
		_spec.ClearField(agent.FieldLastOnlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SupportedProviders(); ok {
		_spec.SetField(agent.FieldSupportedProviders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldSupportedProviders, value)
		})
	}
	if _u.mutation.SupportedProvidersCleared() {
		_spec.ClearField(agent.FieldSupportedProviders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(agent.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldCapabilities, value)
		})
	}
	if _u.mutation.CapabilitiesCleared() {
		_spec.ClearField(agent.FieldCapabilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaxConcurrentTasks(); ok {
		_spec.SetField(agent.FieldMaxConcurrentTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrentTasks(); ok {
		_spec.AddField(agent.FieldMaxConcurrentTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(agent.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(agent.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(agent.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(agent.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceLimits(); ok {
		_spec.SetField(agent.FieldResourceLimits, field.TypeJSON, value)
	}
	if _u.mutation.ResourceLimitsCleared() {
		_spec.ClearField(agent.FieldResourceLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.LocalIP(); ok {
		_spec.SetField(agent.FieldLocalIP, field.TypeString, value)
	}
	if _u.mutation.LocalIPCleared() {
		_spec.ClearField(agent.FieldLocalIP, field.TypeString)
	}
	if value, ok := _u.mutation.PublicIP(); ok {
		_spec.SetField(agent.FieldPublicIP, field.TypeString, value)
	}
	if _u.mutation.PublicIPCleared() {
		_spec.ClearField(agent.FieldPublicIP, field.TypeString)
	}
	if value, ok := _u.mutation.NetworkSegments(); ok {
		_spec.SetField(agent.FieldNetworkSegments, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNetworkSegments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldNetworkSegments, value)
		})
	}
	if _u.mutation.NetworkSegmentsCleared() {
		_spec.ClearField(agent.FieldNetworkSegments, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActiveSessions(); ok {
		_spec.SetField(agent.FieldActiveSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveSessions(); ok {
		_spec.AddField(agent.FieldActiveSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CPUUsage(); ok {
		_spec.SetField(agent.FieldCPUUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCPUUsage(); ok {
		_spec.AddField(agent.FieldCPUUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemoryUsage(); ok {
		_spec.SetField(agent.FieldMemoryUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemoryUsage(); ok {
		_spec.AddField(agent.FieldMemoryUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(agent.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(agent.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessfulRequests(); ok {
		_spec.SetField(agent.FieldSuccessfulRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessfulRequests(); ok {
		_spec.AddField(agent.FieldSuccessfulRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FailedRequests(); ok {
		_spec.SetField(agent.FieldFailedRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFailedRequests(); ok {
		_spec.AddField(agent.FieldFailedRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(agent.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(agent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(agent.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(agent.FieldLastError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdateOne) SetUpdatedAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdateOne) SetStatus(v uint8) *AgentUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableStatus(v *uint8) *AgentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AgentUpdateOne) AddStatus(v int8) *AgentUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *AgentUpdateOne) ClearStatus() *AgentUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *AgentUpdateOne) SetName(v string) *AgentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableName(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentUpdateOne) SetAgentID(v string) *AgentUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableAgentID(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *AgentUpdateOne) SetHost(v string) *AgentUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableHost(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *AgentUpdateOne) SetPort(v int) *AgentUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillablePort(v *int) *AgentUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *AgentUpdateOne) AddPort(v int) *AgentUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *AgentUpdateOne) SetAPIKey(v string) *AgentUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableAPIKey(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentUpdateOne) SetDescription(v string) *AgentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableDescription(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AgentUpdateOne) ClearDescription() *AgentUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetAgentStatus sets the "agent_status" field.
func (_u *AgentUpdateOne) SetAgentStatus(v agent.AgentStatus) *AgentUpdateOne {
	_u.mutation.SetAgentStatus(v)
	return _u
}

// SetNillableAgentStatus sets the "agent_status" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableAgentStatus(v *agent.AgentStatus) *AgentUpdateOne {
	if v != nil {
		_u.SetAgentStatus(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *AgentUpdateOne) SetLastHeartbeat(v time.Time) *AgentUpdateOne {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableLastHeartbeat(v *time.Time) *AgentUpdateOne {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// ClearLastHeartbeat clears the value of the "last_heartbeat" field.
func (_u *AgentUpdateOne) ClearLastHeartbeat() *AgentUpdateOne {
	_u.mutation.ClearLastHeartbeat()
	return _u
}

// SetHeartbeatInterval sets the "heartbeat_interval" field.
func (_u *AgentUpdateOne) SetHeartbeatInterval(v int) *AgentUpdateOne {
	_u.mutation.ResetHeartbeatInterval()
	_u.mutation.SetHeartbeatInterval(v)
	return _u
}

// SetNillableHeartbeatInterval sets the "heartbeat_interval" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableHeartbeatInterval(v *int) *AgentUpdateOne {
	if v != nil {
		_u.SetHeartbeatInterval(*v)
	}
	return _u
}

// AddHeartbeatInterval adds value to the "heartbeat_interval" field.
func (_u *AgentUpdateOne) AddHeartbeatInterval(v int) *AgentUpdateOne {
	_u.mutation.AddHeartbeatInterval(v)
	return _u
}

// SetLastOnlineAt sets the "last_online_at" field.
func (_u *AgentUpdateOne) SetLastOnlineAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetLastOnlineAt(v)
	return _u
}

// SetNillableLastOnlineAt sets the "last_online_at" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableLastOnlineAt(v *time.Time) *AgentUpdateOne {
	if v != nil {
		_u.SetLastOnlineAt(*v)
	}
	return _u
}

// ClearLastOnlineAt clears the value of the "last_online_at" field.
func (_u *AgentUpdateOne) ClearLastOnlineAt() *AgentUpdateOne {
	_u.mutation.ClearLastOnlineAt()
	return _u
}

// SetSupportedProviders sets the "supported_providers" field.
func (_u *AgentUpdateOne) SetSupportedProviders(v []string) *AgentUpdateOne {
	_u.mutation.SetSupportedProviders(v)
	return _u
}

// AppendSupportedProviders appends value to the "supported_providers" field.
func (_u *AgentUpdateOne) AppendSupportedProviders(v []string) *AgentUpdateOne {
	_u.mutation.AppendSupportedProviders(v)
	return _u
}

// ClearSupportedProviders clears the value of the "supported_providers" field.
func (_u *AgentUpdateOne) ClearSupportedProviders() *AgentUpdateOne {
	_u.mutation.ClearSupportedProviders()
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *AgentUpdateOne) SetCapabilities(v []string) *AgentUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *AgentUpdateOne) AppendCapabilities(v []string) *AgentUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// ClearCapabilities clears the value of the "capabilities" field.
func (_u *AgentUpdateOne) ClearCapabilities() *AgentUpdateOne {
	_u.mutation.ClearCapabilities()
	return _u
}

// SetMaxConcurrentTasks sets the "max_concurrent_tasks" field.
func (_u *AgentUpdateOne) SetMaxConcurrentTasks(v int) *AgentUpdateOne {
	_u.mutation.ResetMaxConcurrentTasks()
	_u.mutation.SetMaxConcurrentTasks(v)
	return _u
}

// SetNillableMaxConcurrentTasks sets the "max_concurrent_tasks" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableMaxConcurrentTasks(v *int) *AgentUpdateOne {
	if v != nil {
		_u.SetMaxConcurrentTasks(*v)
	}
	return _u
}

// AddMaxConcurrentTasks adds value to the "max_concurrent_tasks" field.
func (_u *AgentUpdateOne) AddMaxConcurrentTasks(v int) *AgentUpdateOne {
	_u.mutation.AddMaxConcurrentTasks(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *AgentUpdateOne) SetTags(v []string) *AgentUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *AgentUpdateOne) AppendTags(v []string) *AgentUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *AgentUpdateOne) ClearTags() *AgentUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetRegion sets the "region" field.
func (_u *AgentUpdateOne) SetRegion(v string) *AgentUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableRegion(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *AgentUpdateOne) ClearRegion() *AgentUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// SetResourceLimits sets the "resource_limits" field.
func (_u *AgentUpdateOne) SetResourceLimits(v map[string]interface{}) *AgentUpdateOne {
	_u.mutation.SetResourceLimits(v)
	return _u
}

// ClearResourceLimits clears the value of the "resource_limits" field.
func (_u *AgentUpdateOne) ClearResourceLimits() *AgentUpdateOne {
	_u.mutation.ClearResourceLimits()
	return _u
}

// SetLocalIP sets the "local_ip" field.
func (_u *AgentUpdateOne) SetLocalIP(v string) *AgentUpdateOne {
	_u.mutation.SetLocalIP(v)
	return _u
}

// SetNillableLocalIP sets the "local_ip" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableLocalIP(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetLocalIP(*v)
	}
	return _u
}

// ClearLocalIP clears the value of the "local_ip" field.
func (_u *AgentUpdateOne) ClearLocalIP() *AgentUpdateOne {
	_u.mutation.ClearLocalIP()
	return _u
}

// SetPublicIP sets the "public_ip" field.
func (_u *AgentUpdateOne) SetPublicIP(v string) *AgentUpdateOne {
	_u.mutation.SetPublicIP(v)
	return _u
}

// SetNillablePublicIP sets the "public_ip" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillablePublicIP(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetPublicIP(*v)
	}
	return _u
}

// ClearPublicIP clears the value of the "public_ip" field.
func (_u *AgentUpdateOne) ClearPublicIP() *AgentUpdateOne {
	_u.mutation.ClearPublicIP()
	return _u
}

// SetNetworkSegments sets the "network_segments" field.
func (_u *AgentUpdateOne) SetNetworkSegments(v []string) *AgentUpdateOne {
	_u.mutation.SetNetworkSegments(v)
	return _u
}

// AppendNetworkSegments appends value to the "network_segments" field.
func (_u *AgentUpdateOne) AppendNetworkSegments(v []string) *AgentUpdateOne {
	_u.mutation.AppendNetworkSegments(v)
	return _u
}

// ClearNetworkSegments clears the value of the "network_segments" field.
func (_u *AgentUpdateOne) ClearNetworkSegments() *AgentUpdateOne {
	_u.mutation.ClearNetworkSegments()
	return _u
}

// SetActiveSessions sets the "active_sessions" field.
func (_u *AgentUpdateOne) SetActiveSessions(v int) *AgentUpdateOne {
	_u.mutation.ResetActiveSessions()
	_u.mutation.SetActiveSessions(v)
	return _u
}

// SetNillableActiveSessions sets the "active_sessions" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableActiveSessions(v *int) *AgentUpdateOne {
	if v != nil {
		_u.SetActiveSessions(*v)
	}
	return _u
}

// AddActiveSessions adds value to the "active_sessions" field.
func (_u *AgentUpdateOne) AddActiveSessions(v int) *AgentUpdateOne {
	_u.mutation.AddActiveSessions(v)
	return _u
}

// SetCPUUsage sets the "cpu_usage" field.
func (_u *AgentUpdateOne) SetCPUUsage(v float64) *AgentUpdateOne {
	_u.mutation.ResetCPUUsage()
	_u.mutation.SetCPUUsage(v)
	return _u
}

// SetNillableCPUUsage sets the "cpu_usage" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableCPUUsage(v *float64) *AgentUpdateOne {
	if v != nil {
		_u.SetCPUUsage(*v)
	}
	return _u
}

// AddCPUUsage adds value to the "cpu_usage" field.
func (_u *AgentUpdateOne) AddCPUUsage(v float64) *AgentUpdateOne {
	_u.mutation.AddCPUUsage(v)
	return _u
}

// SetMemoryUsage sets the "memory_usage" field.
func (_u *AgentUpdateOne) SetMemoryUsage(v float64) *AgentUpdateOne {
	_u.mutation.ResetMemoryUsage()
	_u.mutation.SetMemoryUsage(v)
	return _u
}

// SetNillableMemoryUsage sets the "memory_usage" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableMemoryUsage(v *float64) *AgentUpdateOne {
	if v != nil {
		_u.SetMemoryUsage(*v)
	}
	return _u
}

// AddMemoryUsage adds value to the "memory_usage" field.
func (_u *AgentUpdateOne) AddMemoryUsage(v float64) *AgentUpdateOne {
	_u.mutation.AddMemoryUsage(v)
	return _u
}

// SetTotalRequests sets the "total_requests" field.
func (_u *AgentUpdateOne) SetTotalRequests(v int64) *AgentUpdateOne {
	_u.mutation.ResetTotalRequests()
	_u.mutation.SetTotalRequests(v)
	return _u
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableTotalRequests(v *int64) *AgentUpdateOne {
	if v != nil {
		_u.SetTotalRequests(*v)
	}
	return _u
}

// AddTotalRequests adds value to the "total_requests" field.
func (_u *AgentUpdateOne) AddTotalRequests(v int64) *AgentUpdateOne {
	_u.mutation.AddTotalRequests(v)
	return _u
}

// SetSuccessfulRequests sets the "successful_requests" field.
func (_u *AgentUpdateOne) SetSuccessfulRequests(v int64) *AgentUpdateOne {
	_u.mutation.ResetSuccessfulRequests()
	_u.mutation.SetSuccessfulRequests(v)
	return _u
}

// SetNillableSuccessfulRequests sets the "successful_requests" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableSuccessfulRequests(v *int64) *AgentUpdateOne {
	if v != nil {
		_u.SetSuccessfulRequests(*v)
	}
	return _u
}

// AddSuccessfulRequests adds value to the "successful_requests" field.
func (_u *AgentUpdateOne) AddSuccessfulRequests(v int64) *AgentUpdateOne {
	_u.mutation.AddSuccessfulRequests(v)
	return _u
}

// SetFailedRequests sets the "failed_requests" field.
func (_u *AgentUpdateOne) SetFailedRequests(v int64) *AgentUpdateOne {
	_u.mutation.ResetFailedRequests()
	_u.mutation.SetFailedRequests(v)
	return _u
}

// SetNillableFailedRequests sets the "failed_requests" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableFailedRequests(v *int64) *AgentUpdateOne {
	if v != nil {
		_u.SetFailedRequests(*v)
	}
	return _u
}

// AddFailedRequests adds value to the "failed_requests" field.
func (_u *AgentUpdateOne) AddFailedRequests(v int64) *AgentUpdateOne {
	_u.mutation.AddFailedRequests(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentUpdateOne) SetVersion(v string) *AgentUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableVersion(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *AgentUpdateOne) ClearVersion() *AgentUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *AgentUpdateOne) SetMetadata(v map[string]interface{}) *AgentUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *AgentUpdateOne) ClearMetadata() *AgentUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *AgentUpdateOne) SetLastError(v string) *AgentUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableLastError(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *AgentUpdateOne) ClearLastError() *AgentUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AgentID(); ok {
		if err := agent.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "Agent.agent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := agent.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Agent.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKey(); ok {
		if err := agent.APIKeyValidator(v); err != nil {
			return &ValidationError{Name: "api_key", err: fmt.Errorf(`ent: validator failed for field "Agent.api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := agent.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Agent.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AgentStatus(); ok {
		if err := agent.AgentStatusValidator(v); err != nil {
			return &ValidationError{Name: "agent_status", err: fmt.Errorf(`ent: validator failed for field "Agent.agent_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := agent.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Agent.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalIP(); ok {
		if err := agent.LocalIPValidator(v); err != nil {
			return &ValidationError{Name: "local_ip", err: fmt.Errorf(`ent: validator failed for field "Agent.local_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicIP(); ok {
		if err := agent.PublicIPValidator(v); err != nil {
			return &ValidationError{Name: "public_ip", err: fmt.Errorf(`ent: validator failed for field "Agent.public_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := agent.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Agent.version": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(agent.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(agent.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentID(); ok {
		_spec.SetField(agent.FieldAgentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(agent.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(agent.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(agent.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(agent.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agent.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(agent.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.AgentStatus(); ok {
		_spec.SetField(agent.FieldAgentStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(agent.FieldLastHeartbeat, field.TypeTime, value)
	}
	if _u.mutation.LastHeartbeatCleared() {
		_spec.ClearField(agent.FieldLastHeartbeat, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatInterval(); ok {
		_spec.SetField(agent.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeartbeatInterval(); ok {
		_spec.AddField(agent.FieldHeartbeatInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastOnlineAt(); ok {
		_spec.SetField(agent.FieldLastOnlineAt, field.TypeTime, value)
	}
	if _u.mutation.LastOnlineAtCleared() {
		_spec.ClearField(agent.FieldLastOnlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SupportedProviders(); ok {
		_spec.SetField(agent.FieldSupportedProviders, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedProviders(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldSupportedProviders, value)
		})
	}
	if _u.mutation.SupportedProvidersCleared() {
		_spec.ClearField(agent.FieldSupportedProviders, field.TypeJSON)
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(agent.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldCapabilities, value)
		})
	}
	if _u.mutation.CapabilitiesCleared() {
		_spec.ClearField(agent.FieldCapabilities, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaxConcurrentTasks(); ok {
		_spec.SetField(agent.FieldMaxConcurrentTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConcurrentTasks(); ok {
		_spec.AddField(agent.FieldMaxConcurrentTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(agent.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(agent.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(agent.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(agent.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.ResourceLimits(); ok {
		_spec.SetField(agent.FieldResourceLimits, field.TypeJSON, value)
	}
	if _u.mutation.ResourceLimitsCleared() {
		_spec.ClearField(agent.FieldResourceLimits, field.TypeJSON)
	}
	if value, ok := _u.mutation.LocalIP(); ok {
		_spec.SetField(agent.FieldLocalIP, field.TypeString, value)
	}
	if _u.mutation.LocalIPCleared() {
		_spec.ClearField(agent.FieldLocalIP, field.TypeString)
	}
	if value, ok := _u.mutation.PublicIP(); ok {
		_spec.SetField(agent.FieldPublicIP, field.TypeString, value)
	}
	if _u.mutation.PublicIPCleared() {
		_spec.ClearField(agent.FieldPublicIP, field.TypeString)
	}
	if value, ok := _u.mutation.NetworkSegments(); ok {
		_spec.SetField(agent.FieldNetworkSegments, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNetworkSegments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldNetworkSegments, value)
		})
	}
	if _u.mutation.NetworkSegmentsCleared() {
		_spec.ClearField(agent.FieldNetworkSegments, field.TypeJSON)
	}
	if value, ok := _u.mutation.ActiveSessions(); ok {
		_spec.SetField(agent.FieldActiveSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveSessions(); ok {
		_spec.AddField(agent.FieldActiveSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CPUUsage(); ok {
		_spec.SetField(agent.FieldCPUUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCPUUsage(); ok {
		_spec.AddField(agent.FieldCPUUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MemoryUsage(); ok {
		_spec.SetField(agent.FieldMemoryUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMemoryUsage(); ok {
		_spec.AddField(agent.FieldMemoryUsage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalRequests(); ok {
		_spec.SetField(agent.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalRequests(); ok {
		_spec.AddField(agent.FieldTotalRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SuccessfulRequests(); ok {
		_spec.SetField(agent.FieldSuccessfulRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSuccessfulRequests(); ok {
		_spec.AddField(agent.FieldSuccessfulRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FailedRequests(); ok {
		_spec.SetField(agent.FieldFailedRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFailedRequests(); ok {
		_spec.AddField(agent.FieldFailedRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(agent.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(agent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(agent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(agent.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(agent.FieldLastError, field.TypeString)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
