// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/credentialref"
	"github.com/coder-lulu/newbee-ops-rpc/ent/predicate"
)

// CredentialRefUpdate is the builder for updating CredentialRef entities.
type CredentialRefUpdate struct {
	config
	hooks    []Hook
	mutation *CredentialRefMutation
}

// Where appends a list predicates to the CredentialRefUpdate builder.
func (_u *CredentialRefUpdate) Where(ps ...predicate.CredentialRef) *CredentialRefUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialRefUpdate) SetUpdatedAt(v time.Time) *CredentialRefUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CredentialRefUpdate) SetStatus(v uint8) *CredentialRefUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CredentialRefUpdate) SetNillableStatus(v *uint8) *CredentialRefUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CredentialRefUpdate) AddStatus(v int8) *CredentialRefUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CredentialRefUpdate) ClearStatus() *CredentialRefUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CredentialRefUpdate) SetProvider(v string) *CredentialRefUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CredentialRefUpdate) SetNillableProvider(v *string) *CredentialRefUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetRef sets the "ref" field.
func (_u *CredentialRefUpdate) SetRef(v string) *CredentialRefUpdate {
	_u.mutation.SetRef(v)
	return _u
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_u *CredentialRefUpdate) SetNillableRef(v *string) *CredentialRefUpdate {
	if v != nil {
		_u.SetRef(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *CredentialRefUpdate) SetScope(v string) *CredentialRefUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *CredentialRefUpdate) SetNillableScope(v *string) *CredentialRefUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *CredentialRefUpdate) ClearScope() *CredentialRefUpdate {
	_u.mutation.ClearScope()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CredentialRefUpdate) SetCreatedBy(v string) *CredentialRefUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CredentialRefUpdate) SetNillableCreatedBy(v *string) *CredentialRefUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *CredentialRefUpdate) ClearCreatedBy() *CredentialRefUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetTags sets the "tags" field.
func (_u *CredentialRefUpdate) SetTags(v map[string]string) *CredentialRefUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CredentialRefUpdate) ClearTags() *CredentialRefUpdate {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the CredentialRefMutation object of the builder.
func (_u *CredentialRefUpdate) Mutation() *CredentialRefMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CredentialRefUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialRefUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CredentialRefUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialRefUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialRefUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentialref.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CredentialRefUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(credentialref.Table, credentialref.Columns, sqlgraph.NewFieldSpec(credentialref.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialref.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(credentialref.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(credentialref.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(credentialref.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(credentialref.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ref(); ok {
		_spec.SetField(credentialref.FieldRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(credentialref.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(credentialref.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(credentialref.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(credentialref.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(credentialref.FieldTags, field.TypeJSON, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(credentialref.FieldTags, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CredentialRefUpdateOne is the builder for updating a single CredentialRef entity.
type CredentialRefUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CredentialRefMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CredentialRefUpdateOne) SetUpdatedAt(v time.Time) *CredentialRefUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CredentialRefUpdateOne) SetStatus(v uint8) *CredentialRefUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CredentialRefUpdateOne) SetNillableStatus(v *uint8) *CredentialRefUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *CredentialRefUpdateOne) AddStatus(v int8) *CredentialRefUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *CredentialRefUpdateOne) ClearStatus() *CredentialRefUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CredentialRefUpdateOne) SetProvider(v string) *CredentialRefUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CredentialRefUpdateOne) SetNillableProvider(v *string) *CredentialRefUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetRef sets the "ref" field.
func (_u *CredentialRefUpdateOne) SetRef(v string) *CredentialRefUpdateOne {
	_u.mutation.SetRef(v)
	return _u
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_u *CredentialRefUpdateOne) SetNillableRef(v *string) *CredentialRefUpdateOne {
	if v != nil {
		_u.SetRef(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *CredentialRefUpdateOne) SetScope(v string) *CredentialRefUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *CredentialRefUpdateOne) SetNillableScope(v *string) *CredentialRefUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *CredentialRefUpdateOne) ClearScope() *CredentialRefUpdateOne {
	_u.mutation.ClearScope()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CredentialRefUpdateOne) SetCreatedBy(v string) *CredentialRefUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CredentialRefUpdateOne) SetNillableCreatedBy(v *string) *CredentialRefUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *CredentialRefUpdateOne) ClearCreatedBy() *CredentialRefUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetTags sets the "tags" field.
func (_u *CredentialRefUpdateOne) SetTags(v map[string]string) *CredentialRefUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CredentialRefUpdateOne) ClearTags() *CredentialRefUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the CredentialRefMutation object of the builder.
func (_u *CredentialRefUpdateOne) Mutation() *CredentialRefMutation {
	return _u.mutation
}

// Where appends a list predicates to the CredentialRefUpdate builder.
func (_u *CredentialRefUpdateOne) Where(ps ...predicate.CredentialRef) *CredentialRefUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CredentialRefUpdateOne) Select(field string, fields ...string) *CredentialRefUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CredentialRef entity.
func (_u *CredentialRefUpdateOne) Save(ctx context.Context) (*CredentialRef, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CredentialRefUpdateOne) SaveX(ctx context.Context) *CredentialRef {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CredentialRefUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CredentialRefUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CredentialRefUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := credentialref.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *CredentialRefUpdateOne) sqlSave(ctx context.Context) (_node *CredentialRef, err error) {
	_spec := sqlgraph.NewUpdateSpec(credentialref.Table, credentialref.Columns, sqlgraph.NewFieldSpec(credentialref.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CredentialRef.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, credentialref.FieldID)
		for _, f := range fields {
			if !credentialref.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != credentialref.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(credentialref.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(credentialref.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(credentialref.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(credentialref.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(credentialref.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Ref(); ok {
		_spec.SetField(credentialref.FieldRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(credentialref.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(credentialref.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(credentialref.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(credentialref.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(credentialref.FieldTags, field.TypeJSON, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(credentialref.FieldTags, field.TypeJSON)
	}
	_node = &CredentialRef{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{credentialref.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
