// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-ops-rpc/ent/proxy"
)

// Proxy is the model entity for the Proxy schema.
type Proxy struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// Proxy唯一标识（由Proxy生成，格式：proxy-{uuid}）
	WorkerID string `json:"worker_id,omitempty"`
	// Proxy友好名称
	Name string `json:"name,omitempty"`
	// Proxy IP地址
	IP string `json:"ip,omitempty"`
	// Proxy服务端口
	Port int `json:"port,omitempty"`
	// Proxy版本号
	Version string `json:"version,omitempty"`
	// 地理区域（如：cn-beijing, us-west-1）
	Region string `json:"region,omitempty"`
	// 可用区（如：az-1, az-2）
	Zone string `json:"zone,omitempty"`
	// 支持的协议能力 [ssh, telnet, rdp, ipmi, snmp]
	Capabilities []string `json:"capabilities,omitempty"`
	// 标签列表，用于分类和筛选
	Tags []string `json:"tags,omitempty"`
	// 服务端点映射 {"http":"http://...", "ws":"ws://..."}
	Endpoints map[string]string `json:"endpoints,omitempty"`
	// Proxy运行状态
	WorkerStatus proxy.WorkerStatus `json:"worker_status,omitempty"`
	// 最后心跳时间
	LastHeartbeat *time.Time `json:"last_heartbeat,omitempty"`
	// 首次注册时间
	RegisterTime *time.Time `json:"register_time,omitempty"`
	// 负载均衡权重（1-1000），越大分配越多
	Weight int `json:"weight,omitempty"`
	// 优先级，数字越大优先级越高
	Priority int `json:"priority,omitempty"`
	// CPU使用率（0-100）
	CPUUsage float64 `json:"cpu_usage,omitempty"`
	// 内存使用率（0-100）
	MemoryUsage float64 `json:"memory_usage,omitempty"`
	// 磁盘使用率（0-100）
	DiskUsage float64 `json:"disk_usage,omitempty"`
	// 网络入流量（字节）
	NetworkIn uint64 `json:"network_in,omitempty"`
	// 网络出流量（字节）
	NetworkOut uint64 `json:"network_out,omitempty"`
	// 当前活跃会话数
	ActiveSessions int `json:"active_sessions,omitempty"`
	// 总请求次数
	TotalRequests uint64 `json:"total_requests,omitempty"`
	// 成功请求次数
	SuccessCount uint64 `json:"success_count,omitempty"`
	// 失败请求次数
	FailureCount uint64 `json:"failure_count,omitempty"`
	// 最大并发会话数
	MaxSessions int `json:"max_sessions,omitempty"`
	// 连续健康检查失败次数
	HealthCheckFailures int `json:"health_check_failures,omitempty"`
	// 最后健康检查时间
	LastHealthCheck *time.Time `json:"last_health_check,omitempty"`
	// 健康检查URL（为空则不主动探测）
	HealthCheckURL string `json:"health_check_url,omitempty"`
	// 本地IP地址
	LocalIP string `json:"local_ip,omitempty"`
	// 公网IP地址
	PublicIP string `json:"public_ip,omitempty"`
	// 管理的网段列表 ["192.168.1.0/24", "10.0.0.0/8"]
	NetworkSegments []string `json:"network_segments,omitempty"`
	// 扩展元数据（用户自定义字段）
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// 最后错误信息
	LastError    string `json:"last_error,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Proxy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxy.FieldCapabilities, proxy.FieldTags, proxy.FieldEndpoints, proxy.FieldNetworkSegments, proxy.FieldMetadata:
			values[i] = new([]byte)
		case proxy.FieldCPUUsage, proxy.FieldMemoryUsage, proxy.FieldDiskUsage:
			values[i] = new(sql.NullFloat64)
		case proxy.FieldID, proxy.FieldTenantID, proxy.FieldStatus, proxy.FieldPort, proxy.FieldWeight, proxy.FieldPriority, proxy.FieldNetworkIn, proxy.FieldNetworkOut, proxy.FieldActiveSessions, proxy.FieldTotalRequests, proxy.FieldSuccessCount, proxy.FieldFailureCount, proxy.FieldMaxSessions, proxy.FieldHealthCheckFailures:
			values[i] = new(sql.NullInt64)
		case proxy.FieldWorkerID, proxy.FieldName, proxy.FieldIP, proxy.FieldVersion, proxy.FieldRegion, proxy.FieldZone, proxy.FieldWorkerStatus, proxy.FieldHealthCheckURL, proxy.FieldLocalIP, proxy.FieldPublicIP, proxy.FieldLastError:
			values[i] = new(sql.NullString)
		case proxy.FieldCreatedAt, proxy.FieldUpdatedAt, proxy.FieldLastHeartbeat, proxy.FieldRegisterTime, proxy.FieldLastHealthCheck:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Proxy fields.
func (_m *Proxy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case proxy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxy.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case proxy.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case proxy.FieldWorkerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field worker_id", values[i])
			} else if value.Valid {
				_m.WorkerID = value.String
			}
		case proxy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxy.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case proxy.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case proxy.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case proxy.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case proxy.FieldZone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zone", values[i])
			} else if value.Valid {
				_m.Zone = value.String
			}
		case proxy.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case proxy.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case proxy.FieldEndpoints:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field endpoints", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Endpoints); err != nil {
					return fmt.Errorf("unmarshal field endpoints: %w", err)
				}
			}
		case proxy.FieldWorkerStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field worker_status", values[i])
			} else if value.Valid {
				_m.WorkerStatus = proxy.WorkerStatus(value.String)
			}
		case proxy.FieldLastHeartbeat:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_heartbeat", values[i])
			} else if value.Valid {
				_m.LastHeartbeat = new(time.Time)
				*_m.LastHeartbeat = value.Time
			}
		case proxy.FieldRegisterTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field register_time", values[i])
			} else if value.Valid {
				_m.RegisterTime = new(time.Time)
				*_m.RegisterTime = value.Time
			}
		case proxy.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case proxy.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case proxy.FieldCPUUsage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cpu_usage", values[i])
			} else if value.Valid {
				_m.CPUUsage = value.Float64
			}
		case proxy.FieldMemoryUsage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field memory_usage", values[i])
			} else if value.Valid {
				_m.MemoryUsage = value.Float64
			}
		case proxy.FieldDiskUsage:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field disk_usage", values[i])
			} else if value.Valid {
				_m.DiskUsage = value.Float64
			}
		case proxy.FieldNetworkIn:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field network_in", values[i])
			} else if value.Valid {
				_m.NetworkIn = uint64(value.Int64)
			}
		case proxy.FieldNetworkOut:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field network_out", values[i])
			} else if value.Valid {
				_m.NetworkOut = uint64(value.Int64)
			}
		case proxy.FieldActiveSessions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_sessions", values[i])
			} else if value.Valid {
				_m.ActiveSessions = int(value.Int64)
			}
		case proxy.FieldTotalRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_requests", values[i])
			} else if value.Valid {
				_m.TotalRequests = uint64(value.Int64)
			}
		case proxy.FieldSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_count", values[i])
			} else if value.Valid {
				_m.SuccessCount = uint64(value.Int64)
			}
		case proxy.FieldFailureCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failure_count", values[i])
			} else if value.Valid {
				_m.FailureCount = uint64(value.Int64)
			}
		case proxy.FieldMaxSessions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_sessions", values[i])
			} else if value.Valid {
				_m.MaxSessions = int(value.Int64)
			}
		case proxy.FieldHealthCheckFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field health_check_failures", values[i])
			} else if value.Valid {
				_m.HealthCheckFailures = int(value.Int64)
			}
		case proxy.FieldLastHealthCheck:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_health_check", values[i])
			} else if value.Valid {
				_m.LastHealthCheck = new(time.Time)
				*_m.LastHealthCheck = value.Time
			}
		case proxy.FieldHealthCheckURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_check_url", values[i])
			} else if value.Valid {
				_m.HealthCheckURL = value.String
			}
		case proxy.FieldLocalIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_ip", values[i])
			} else if value.Valid {
				_m.LocalIP = value.String
			}
		case proxy.FieldPublicIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_ip", values[i])
			} else if value.Valid {
				_m.PublicIP = value.String
			}
		case proxy.FieldNetworkSegments:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field network_segments", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NetworkSegments); err != nil {
					return fmt.Errorf("unmarshal field network_segments: %w", err)
				}
			}
		case proxy.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case proxy.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Proxy.
// This includes values selected through modifiers, order, etc.
func (_m *Proxy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Proxy.
// Note that you need to call Proxy.Unwrap() before calling this method if this Proxy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Proxy) Update() *ProxyUpdateOne {
	return NewProxyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Proxy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Proxy) Unwrap() *Proxy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Proxy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Proxy) String() string {
	var builder strings.Builder
	builder.WriteString("Proxy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("worker_id=")
	builder.WriteString(_m.WorkerID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("zone=")
	builder.WriteString(_m.Zone)
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("endpoints=")
	builder.WriteString(fmt.Sprintf("%v", _m.Endpoints))
	builder.WriteString(", ")
	builder.WriteString("worker_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkerStatus))
	builder.WriteString(", ")
	if v := _m.LastHeartbeat; v != nil {
		builder.WriteString("last_heartbeat=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RegisterTime; v != nil {
		builder.WriteString("register_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("cpu_usage=")
	builder.WriteString(fmt.Sprintf("%v", _m.CPUUsage))
	builder.WriteString(", ")
	builder.WriteString("memory_usage=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemoryUsage))
	builder.WriteString(", ")
	builder.WriteString("disk_usage=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiskUsage))
	builder.WriteString(", ")
	builder.WriteString("network_in=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetworkIn))
	builder.WriteString(", ")
	builder.WriteString("network_out=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetworkOut))
	builder.WriteString(", ")
	builder.WriteString("active_sessions=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActiveSessions))
	builder.WriteString(", ")
	builder.WriteString("total_requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalRequests))
	builder.WriteString(", ")
	builder.WriteString("success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessCount))
	builder.WriteString(", ")
	builder.WriteString("failure_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailureCount))
	builder.WriteString(", ")
	builder.WriteString("max_sessions=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxSessions))
	builder.WriteString(", ")
	builder.WriteString("health_check_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthCheckFailures))
	builder.WriteString(", ")
	if v := _m.LastHealthCheck; v != nil {
		builder.WriteString("last_health_check=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("health_check_url=")
	builder.WriteString(_m.HealthCheckURL)
	builder.WriteString(", ")
	builder.WriteString("local_ip=")
	builder.WriteString(_m.LocalIP)
	builder.WriteString(", ")
	builder.WriteString("public_ip=")
	builder.WriteString(_m.PublicIP)
	builder.WriteString(", ")
	builder.WriteString("network_segments=")
	builder.WriteString(fmt.Sprintf("%v", _m.NetworkSegments))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteByte(')')
	return builder.String()
}

// Proxies is a parsable slice of Proxy.
type Proxies []*Proxy
