// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/predicate"
	"github.com/coder-lulu/newbee-ops-rpc/ent/script"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptcategory"
)

// ScriptCategoryUpdate is the builder for updating ScriptCategory entities.
type ScriptCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *ScriptCategoryMutation
}

// Where appends a list predicates to the ScriptCategoryUpdate builder.
func (_u *ScriptCategoryUpdate) Where(ps ...predicate.ScriptCategory) *ScriptCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptCategoryUpdate) SetUpdatedAt(v time.Time) *ScriptCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ScriptCategoryUpdate) SetDepartmentID(v uint64) *ScriptCategoryUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableDepartmentID(v *uint64) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *ScriptCategoryUpdate) AddDepartmentID(v int64) *ScriptCategoryUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ScriptCategoryUpdate) ClearDepartmentID() *ScriptCategoryUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScriptCategoryUpdate) SetStatus(v uint8) *ScriptCategoryUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableStatus(v *uint8) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ScriptCategoryUpdate) AddStatus(v int8) *ScriptCategoryUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ScriptCategoryUpdate) ClearStatus() *ScriptCategoryUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *ScriptCategoryUpdate) SetName(v string) *ScriptCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableName(v *string) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ScriptCategoryUpdate) SetCode(v string) *ScriptCategoryUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableCode(v *string) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScriptCategoryUpdate) SetDescription(v string) *ScriptCategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableDescription(v *string) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScriptCategoryUpdate) ClearDescription() *ScriptCategoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ScriptCategoryUpdate) SetParentID(v uint64) *ScriptCategoryUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableParentID(v *uint64) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ScriptCategoryUpdate) ClearParentID() *ScriptCategoryUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ScriptCategoryUpdate) SetSortOrder(v uint32) *ScriptCategoryUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableSortOrder(v *uint32) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ScriptCategoryUpdate) AddSortOrder(v int32) *ScriptCategoryUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ScriptCategoryUpdate) SetIcon(v string) *ScriptCategoryUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ScriptCategoryUpdate) SetNillableIcon(v *string) *ScriptCategoryUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *ScriptCategoryUpdate) ClearIcon() *ScriptCategoryUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetParent sets the "parent" edge to the ScriptCategory entity.
func (_u *ScriptCategoryUpdate) SetParent(v *ScriptCategory) *ScriptCategoryUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the ScriptCategory entity by IDs.
func (_u *ScriptCategoryUpdate) AddChildIDs(ids ...uint64) *ScriptCategoryUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the ScriptCategory entity.
func (_u *ScriptCategoryUpdate) AddChildren(v ...*ScriptCategory) *ScriptCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddScriptIDs adds the "scripts" edge to the Script entity by IDs.
func (_u *ScriptCategoryUpdate) AddScriptIDs(ids ...uint64) *ScriptCategoryUpdate {
	_u.mutation.AddScriptIDs(ids...)
	return _u
}

// AddScripts adds the "scripts" edges to the Script entity.
func (_u *ScriptCategoryUpdate) AddScripts(v ...*Script) *ScriptCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScriptIDs(ids...)
}

// Mutation returns the ScriptCategoryMutation object of the builder.
func (_u *ScriptCategoryUpdate) Mutation() *ScriptCategoryMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the ScriptCategory entity.
func (_u *ScriptCategoryUpdate) ClearParent() *ScriptCategoryUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the ScriptCategory entity.
func (_u *ScriptCategoryUpdate) ClearChildren() *ScriptCategoryUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to ScriptCategory entities by IDs.
func (_u *ScriptCategoryUpdate) RemoveChildIDs(ids ...uint64) *ScriptCategoryUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to ScriptCategory entities.
func (_u *ScriptCategoryUpdate) RemoveChildren(v ...*ScriptCategory) *ScriptCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearScripts clears all "scripts" edges to the Script entity.
func (_u *ScriptCategoryUpdate) ClearScripts() *ScriptCategoryUpdate {
	_u.mutation.ClearScripts()
	return _u
}

// RemoveScriptIDs removes the "scripts" edge to Script entities by IDs.
func (_u *ScriptCategoryUpdate) RemoveScriptIDs(ids ...uint64) *ScriptCategoryUpdate {
	_u.mutation.RemoveScriptIDs(ids...)
	return _u
}

// RemoveScripts removes "scripts" edges to Script entities.
func (_u *ScriptCategoryUpdate) RemoveScripts(v ...*Script) *ScriptCategoryUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScriptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScriptCategoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScriptCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptCategoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scriptcategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptCategoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scriptcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := scriptcategory.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := scriptcategory.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := scriptcategory.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.icon": %w`, err)}
		}
	}
	return nil
}

func (_u *ScriptCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptcategory.Table, scriptcategory.Columns, sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scriptcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(scriptcategory.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(scriptcategory.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(scriptcategory.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scriptcategory.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(scriptcategory.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(scriptcategory.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scriptcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(scriptcategory.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scriptcategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scriptcategory.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(scriptcategory.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(scriptcategory.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(scriptcategory.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(scriptcategory.FieldIcon, field.TypeString)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptcategory.ParentTable,
			Columns: []string{scriptcategory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptcategory.ParentTable,
			Columns: []string{scriptcategory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ChildrenTable,
			Columns: []string{scriptcategory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ChildrenTable,
			Columns: []string{scriptcategory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ChildrenTable,
			Columns: []string{scriptcategory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScriptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ScriptsTable,
			Columns: []string{scriptcategory.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScriptsIDs(); len(nodes) > 0 && !_u.mutation.ScriptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ScriptsTable,
			Columns: []string{scriptcategory.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ScriptsTable,
			Columns: []string{scriptcategory.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScriptCategoryUpdateOne is the builder for updating a single ScriptCategory entity.
type ScriptCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScriptCategoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptCategoryUpdateOne) SetUpdatedAt(v time.Time) *ScriptCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ScriptCategoryUpdateOne) SetDepartmentID(v uint64) *ScriptCategoryUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableDepartmentID(v *uint64) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *ScriptCategoryUpdateOne) AddDepartmentID(v int64) *ScriptCategoryUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ScriptCategoryUpdateOne) ClearDepartmentID() *ScriptCategoryUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScriptCategoryUpdateOne) SetStatus(v uint8) *ScriptCategoryUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableStatus(v *uint8) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ScriptCategoryUpdateOne) AddStatus(v int8) *ScriptCategoryUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ScriptCategoryUpdateOne) ClearStatus() *ScriptCategoryUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *ScriptCategoryUpdateOne) SetName(v string) *ScriptCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableName(v *string) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ScriptCategoryUpdateOne) SetCode(v string) *ScriptCategoryUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableCode(v *string) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScriptCategoryUpdateOne) SetDescription(v string) *ScriptCategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableDescription(v *string) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScriptCategoryUpdateOne) ClearDescription() *ScriptCategoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *ScriptCategoryUpdateOne) SetParentID(v uint64) *ScriptCategoryUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableParentID(v *uint64) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *ScriptCategoryUpdateOne) ClearParentID() *ScriptCategoryUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ScriptCategoryUpdateOne) SetSortOrder(v uint32) *ScriptCategoryUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableSortOrder(v *uint32) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ScriptCategoryUpdateOne) AddSortOrder(v int32) *ScriptCategoryUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIcon sets the "icon" field.
func (_u *ScriptCategoryUpdateOne) SetIcon(v string) *ScriptCategoryUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *ScriptCategoryUpdateOne) SetNillableIcon(v *string) *ScriptCategoryUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *ScriptCategoryUpdateOne) ClearIcon() *ScriptCategoryUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetParent sets the "parent" edge to the ScriptCategory entity.
func (_u *ScriptCategoryUpdateOne) SetParent(v *ScriptCategory) *ScriptCategoryUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the ScriptCategory entity by IDs.
func (_u *ScriptCategoryUpdateOne) AddChildIDs(ids ...uint64) *ScriptCategoryUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the ScriptCategory entity.
func (_u *ScriptCategoryUpdateOne) AddChildren(v ...*ScriptCategory) *ScriptCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddScriptIDs adds the "scripts" edge to the Script entity by IDs.
func (_u *ScriptCategoryUpdateOne) AddScriptIDs(ids ...uint64) *ScriptCategoryUpdateOne {
	_u.mutation.AddScriptIDs(ids...)
	return _u
}

// AddScripts adds the "scripts" edges to the Script entity.
func (_u *ScriptCategoryUpdateOne) AddScripts(v ...*Script) *ScriptCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScriptIDs(ids...)
}

// Mutation returns the ScriptCategoryMutation object of the builder.
func (_u *ScriptCategoryUpdateOne) Mutation() *ScriptCategoryMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the ScriptCategory entity.
func (_u *ScriptCategoryUpdateOne) ClearParent() *ScriptCategoryUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the ScriptCategory entity.
func (_u *ScriptCategoryUpdateOne) ClearChildren() *ScriptCategoryUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to ScriptCategory entities by IDs.
func (_u *ScriptCategoryUpdateOne) RemoveChildIDs(ids ...uint64) *ScriptCategoryUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to ScriptCategory entities.
func (_u *ScriptCategoryUpdateOne) RemoveChildren(v ...*ScriptCategory) *ScriptCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearScripts clears all "scripts" edges to the Script entity.
func (_u *ScriptCategoryUpdateOne) ClearScripts() *ScriptCategoryUpdateOne {
	_u.mutation.ClearScripts()
	return _u
}

// RemoveScriptIDs removes the "scripts" edge to Script entities by IDs.
func (_u *ScriptCategoryUpdateOne) RemoveScriptIDs(ids ...uint64) *ScriptCategoryUpdateOne {
	_u.mutation.RemoveScriptIDs(ids...)
	return _u
}

// RemoveScripts removes "scripts" edges to Script entities.
func (_u *ScriptCategoryUpdateOne) RemoveScripts(v ...*Script) *ScriptCategoryUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScriptIDs(ids...)
}

// Where appends a list predicates to the ScriptCategoryUpdate builder.
func (_u *ScriptCategoryUpdateOne) Where(ps ...predicate.ScriptCategory) *ScriptCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScriptCategoryUpdateOne) Select(field string, fields ...string) *ScriptCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScriptCategory entity.
func (_u *ScriptCategoryUpdateOne) Save(ctx context.Context) (*ScriptCategory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptCategoryUpdateOne) SaveX(ctx context.Context) *ScriptCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScriptCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptCategoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scriptcategory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := scriptcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := scriptcategory.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := scriptcategory.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Icon(); ok {
		if err := scriptcategory.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.icon": %w`, err)}
		}
	}
	return nil
}

func (_u *ScriptCategoryUpdateOne) sqlSave(ctx context.Context) (_node *ScriptCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptcategory.Table, scriptcategory.Columns, sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScriptCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scriptcategory.FieldID)
		for _, f := range fields {
			if !scriptcategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scriptcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scriptcategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(scriptcategory.FieldDepartmentID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(scriptcategory.FieldDepartmentID, field.TypeUint64, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(scriptcategory.FieldDepartmentID, field.TypeUint64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scriptcategory.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(scriptcategory.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(scriptcategory.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(scriptcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(scriptcategory.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(scriptcategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(scriptcategory.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(scriptcategory.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(scriptcategory.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(scriptcategory.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(scriptcategory.FieldIcon, field.TypeString)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptcategory.ParentTable,
			Columns: []string{scriptcategory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptcategory.ParentTable,
			Columns: []string{scriptcategory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ChildrenTable,
			Columns: []string{scriptcategory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ChildrenTable,
			Columns: []string{scriptcategory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ChildrenTable,
			Columns: []string{scriptcategory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScriptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ScriptsTable,
			Columns: []string{scriptcategory.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScriptsIDs(); len(nodes) > 0 && !_u.mutation.ScriptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ScriptsTable,
			Columns: []string{scriptcategory.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ScriptsTable,
			Columns: []string{scriptcategory.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScriptCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
