// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/predicate"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecution"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecutiondetail"
)

// ScriptExecutionDetailUpdate is the builder for updating ScriptExecutionDetail entities.
type ScriptExecutionDetailUpdate struct {
	config
	hooks    []Hook
	mutation *ScriptExecutionDetailMutation
}

// Where appends a list predicates to the ScriptExecutionDetailUpdate builder.
func (_u *ScriptExecutionDetailUpdate) Where(ps ...predicate.ScriptExecutionDetail) *ScriptExecutionDetailUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptExecutionDetailUpdate) SetUpdatedAt(v time.Time) *ScriptExecutionDetailUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScriptExecutionDetailUpdate) SetStatus(v uint8) *ScriptExecutionDetailUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableStatus(v *uint8) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ScriptExecutionDetailUpdate) AddStatus(v int8) *ScriptExecutionDetailUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ScriptExecutionDetailUpdate) ClearStatus() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *ScriptExecutionDetailUpdate) SetExecutionID(v uint64) *ScriptExecutionDetailUpdate {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableExecutionID(v *uint64) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetCiID sets the "ci_id" field.
func (_u *ScriptExecutionDetailUpdate) SetCiID(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetCiID(v)
	return _u
}

// SetNillableCiID sets the "ci_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableCiID(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetCiID(*v)
	}
	return _u
}

// SetCiName sets the "ci_name" field.
func (_u *ScriptExecutionDetailUpdate) SetCiName(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetCiName(v)
	return _u
}

// SetNillableCiName sets the "ci_name" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableCiName(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetCiName(*v)
	}
	return _u
}

// ClearCiName clears the value of the "ci_name" field.
func (_u *ScriptExecutionDetailUpdate) ClearCiName() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearCiName()
	return _u
}

// SetCiIP sets the "ci_ip" field.
func (_u *ScriptExecutionDetailUpdate) SetCiIP(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetCiIP(v)
	return _u
}

// SetNillableCiIP sets the "ci_ip" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableCiIP(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetCiIP(*v)
	}
	return _u
}

// ClearCiIP clears the value of the "ci_ip" field.
func (_u *ScriptExecutionDetailUpdate) ClearCiIP() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearCiIP()
	return _u
}

// SetExecStatus sets the "exec_status" field.
func (_u *ScriptExecutionDetailUpdate) SetExecStatus(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetExecStatus(v)
	return _u
}

// SetNillableExecStatus sets the "exec_status" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableExecStatus(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetExecStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ScriptExecutionDetailUpdate) SetStartedAt(v time.Time) *ScriptExecutionDetailUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableStartedAt(v *time.Time) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ScriptExecutionDetailUpdate) ClearStartedAt() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ScriptExecutionDetailUpdate) SetCompletedAt(v time.Time) *ScriptExecutionDetailUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableCompletedAt(v *time.Time) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ScriptExecutionDetailUpdate) ClearCompletedAt() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ScriptExecutionDetailUpdate) SetDurationMs(v uint64) *ScriptExecutionDetailUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableDurationMs(v *uint64) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ScriptExecutionDetailUpdate) AddDurationMs(v int64) *ScriptExecutionDetailUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetOutput sets the "output" field.
func (_u *ScriptExecutionDetailUpdate) SetOutput(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableOutput(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *ScriptExecutionDetailUpdate) ClearOutput() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearOutput()
	return _u
}

// SetErrorOutput sets the "error_output" field.
func (_u *ScriptExecutionDetailUpdate) SetErrorOutput(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetErrorOutput(v)
	return _u
}

// SetNillableErrorOutput sets the "error_output" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableErrorOutput(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetErrorOutput(*v)
	}
	return _u
}

// ClearErrorOutput clears the value of the "error_output" field.
func (_u *ScriptExecutionDetailUpdate) ClearErrorOutput() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearErrorOutput()
	return _u
}

// SetExitCode sets the "exit_code" field.
func (_u *ScriptExecutionDetailUpdate) SetExitCode(v int) *ScriptExecutionDetailUpdate {
	_u.mutation.ResetExitCode()
	_u.mutation.SetExitCode(v)
	return _u
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableExitCode(v *int) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetExitCode(*v)
	}
	return _u
}

// AddExitCode adds value to the "exit_code" field.
func (_u *ScriptExecutionDetailUpdate) AddExitCode(v int) *ScriptExecutionDetailUpdate {
	_u.mutation.AddExitCode(v)
	return _u
}

// ClearExitCode clears the value of the "exit_code" field.
func (_u *ScriptExecutionDetailUpdate) ClearExitCode() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearExitCode()
	return _u
}

// SetFullOutputPath sets the "full_output_path" field.
func (_u *ScriptExecutionDetailUpdate) SetFullOutputPath(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetFullOutputPath(v)
	return _u
}

// SetNillableFullOutputPath sets the "full_output_path" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableFullOutputPath(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetFullOutputPath(*v)
	}
	return _u
}

// ClearFullOutputPath clears the value of the "full_output_path" field.
func (_u *ScriptExecutionDetailUpdate) ClearFullOutputPath() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearFullOutputPath()
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *ScriptExecutionDetailUpdate) SetTaskID(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableTaskID(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *ScriptExecutionDetailUpdate) ClearTaskID() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearTaskID()
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *ScriptExecutionDetailUpdate) SetWorkerID(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableWorkerID(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// ClearWorkerID clears the value of the "worker_id" field.
func (_u *ScriptExecutionDetailUpdate) ClearWorkerID() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearWorkerID()
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ScriptExecutionDetailUpdate) SetProxyID(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableProxyID(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *ScriptExecutionDetailUpdate) ClearProxyID() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearProxyID()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScriptExecutionDetailUpdate) SetErrorMessage(v string) *ScriptExecutionDetailUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableErrorMessage(v *string) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ScriptExecutionDetailUpdate) ClearErrorMessage() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *ScriptExecutionDetailUpdate) SetRetryCount(v uint32) *ScriptExecutionDetailUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdate) SetNillableRetryCount(v *uint32) *ScriptExecutionDetailUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *ScriptExecutionDetailUpdate) AddRetryCount(v int32) *ScriptExecutionDetailUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetExecution sets the "execution" edge to the ScriptExecution entity.
func (_u *ScriptExecutionDetailUpdate) SetExecution(v *ScriptExecution) *ScriptExecutionDetailUpdate {
	return _u.SetExecutionID(v.ID)
}

// Mutation returns the ScriptExecutionDetailMutation object of the builder.
func (_u *ScriptExecutionDetailUpdate) Mutation() *ScriptExecutionDetailMutation {
	return _u.mutation
}

// ClearExecution clears the "execution" edge to the ScriptExecution entity.
func (_u *ScriptExecutionDetailUpdate) ClearExecution() *ScriptExecutionDetailUpdate {
	_u.mutation.ClearExecution()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScriptExecutionDetailUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptExecutionDetailUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScriptExecutionDetailUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptExecutionDetailUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptExecutionDetailUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scriptexecutiondetail.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptExecutionDetailUpdate) check() error {
	if v, ok := _u.mutation.ExecutionID(); ok {
		if err := scriptexecutiondetail.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.execution_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiID(); ok {
		if err := scriptexecutiondetail.CiIDValidator(v); err != nil {
			return &ValidationError{Name: "ci_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.ci_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiName(); ok {
		if err := scriptexecutiondetail.CiNameValidator(v); err != nil {
			return &ValidationError{Name: "ci_name", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.ci_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiIP(); ok {
		if err := scriptexecutiondetail.CiIPValidator(v); err != nil {
			return &ValidationError{Name: "ci_ip", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.ci_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecStatus(); ok {
		if err := scriptexecutiondetail.ExecStatusValidator(v); err != nil {
			return &ValidationError{Name: "exec_status", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.exec_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullOutputPath(); ok {
		if err := scriptexecutiondetail.FullOutputPathValidator(v); err != nil {
			return &ValidationError{Name: "full_output_path", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.full_output_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskID(); ok {
		if err := scriptexecutiondetail.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkerID(); ok {
		if err := scriptexecutiondetail.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.worker_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProxyID(); ok {
		if err := scriptexecutiondetail.ProxyIDValidator(v); err != nil {
			return &ValidationError{Name: "proxy_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.proxy_id": %w`, err)}
		}
	}
	if _u.mutation.ExecutionCleared() && len(_u.mutation.ExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScriptExecutionDetail.execution"`)
	}
	return nil
}

func (_u *ScriptExecutionDetailUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptexecutiondetail.Table, scriptexecutiondetail.Columns, sqlgraph.NewFieldSpec(scriptexecutiondetail.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scriptexecutiondetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scriptexecutiondetail.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(scriptexecutiondetail.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.CiID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCiID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CiName(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCiName, field.TypeString, value)
	}
	if _u.mutation.CiNameCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldCiName, field.TypeString)
	}
	if value, ok := _u.mutation.CiIP(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCiIP, field.TypeString, value)
	}
	if _u.mutation.CiIPCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldCiIP, field.TypeString)
	}
	if value, ok := _u.mutation.ExecStatus(); ok {
		_spec.SetField(scriptexecutiondetail.FieldExecStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(scriptexecutiondetail.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(scriptexecutiondetail.FieldDurationMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(scriptexecutiondetail.FieldDurationMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(scriptexecutiondetail.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorOutput(); ok {
		_spec.SetField(scriptexecutiondetail.FieldErrorOutput, field.TypeString, value)
	}
	if _u.mutation.ErrorOutputCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldErrorOutput, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCode(); ok {
		_spec.SetField(scriptexecutiondetail.FieldExitCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitCode(); ok {
		_spec.AddField(scriptexecutiondetail.FieldExitCode, field.TypeInt, value)
	}
	if _u.mutation.ExitCodeCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldExitCode, field.TypeInt)
	}
	if value, ok := _u.mutation.FullOutputPath(); ok {
		_spec.SetField(scriptexecutiondetail.FieldFullOutputPath, field.TypeString, value)
	}
	if _u.mutation.FullOutputPathCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldFullOutputPath, field.TypeString)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldTaskID, field.TypeString, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldWorkerID, field.TypeString, value)
	}
	if _u.mutation.WorkerIDCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldWorkerID, field.TypeString)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldProxyID, field.TypeString, value)
	}
	if _u.mutation.ProxyIDCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldProxyID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(scriptexecutiondetail.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(scriptexecutiondetail.FieldRetryCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(scriptexecutiondetail.FieldRetryCount, field.TypeUint32, value)
	}
	if _u.mutation.ExecutionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptexecutiondetail.ExecutionTable,
			Columns: []string{scriptexecutiondetail.ExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptexecution.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptexecutiondetail.ExecutionTable,
			Columns: []string{scriptexecutiondetail.ExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptexecution.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptexecutiondetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScriptExecutionDetailUpdateOne is the builder for updating a single ScriptExecutionDetail entity.
type ScriptExecutionDetailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScriptExecutionDetailMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptExecutionDetailUpdateOne) SetUpdatedAt(v time.Time) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScriptExecutionDetailUpdateOne) SetStatus(v uint8) *ScriptExecutionDetailUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableStatus(v *uint8) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ScriptExecutionDetailUpdateOne) AddStatus(v int8) *ScriptExecutionDetailUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearStatus() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *ScriptExecutionDetailUpdateOne) SetExecutionID(v uint64) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableExecutionID(v *uint64) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetCiID sets the "ci_id" field.
func (_u *ScriptExecutionDetailUpdateOne) SetCiID(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetCiID(v)
	return _u
}

// SetNillableCiID sets the "ci_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableCiID(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetCiID(*v)
	}
	return _u
}

// SetCiName sets the "ci_name" field.
func (_u *ScriptExecutionDetailUpdateOne) SetCiName(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetCiName(v)
	return _u
}

// SetNillableCiName sets the "ci_name" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableCiName(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetCiName(*v)
	}
	return _u
}

// ClearCiName clears the value of the "ci_name" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearCiName() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearCiName()
	return _u
}

// SetCiIP sets the "ci_ip" field.
func (_u *ScriptExecutionDetailUpdateOne) SetCiIP(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetCiIP(v)
	return _u
}

// SetNillableCiIP sets the "ci_ip" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableCiIP(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetCiIP(*v)
	}
	return _u
}

// ClearCiIP clears the value of the "ci_ip" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearCiIP() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearCiIP()
	return _u
}

// SetExecStatus sets the "exec_status" field.
func (_u *ScriptExecutionDetailUpdateOne) SetExecStatus(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetExecStatus(v)
	return _u
}

// SetNillableExecStatus sets the "exec_status" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableExecStatus(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetExecStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ScriptExecutionDetailUpdateOne) SetStartedAt(v time.Time) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableStartedAt(v *time.Time) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearStartedAt() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *ScriptExecutionDetailUpdateOne) SetCompletedAt(v time.Time) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableCompletedAt(v *time.Time) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearCompletedAt() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *ScriptExecutionDetailUpdateOne) SetDurationMs(v uint64) *ScriptExecutionDetailUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableDurationMs(v *uint64) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *ScriptExecutionDetailUpdateOne) AddDurationMs(v int64) *ScriptExecutionDetailUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetOutput sets the "output" field.
func (_u *ScriptExecutionDetailUpdateOne) SetOutput(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetOutput(v)
	return _u
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableOutput(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetOutput(*v)
	}
	return _u
}

// ClearOutput clears the value of the "output" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearOutput() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearOutput()
	return _u
}

// SetErrorOutput sets the "error_output" field.
func (_u *ScriptExecutionDetailUpdateOne) SetErrorOutput(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetErrorOutput(v)
	return _u
}

// SetNillableErrorOutput sets the "error_output" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableErrorOutput(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetErrorOutput(*v)
	}
	return _u
}

// ClearErrorOutput clears the value of the "error_output" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearErrorOutput() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearErrorOutput()
	return _u
}

// SetExitCode sets the "exit_code" field.
func (_u *ScriptExecutionDetailUpdateOne) SetExitCode(v int) *ScriptExecutionDetailUpdateOne {
	_u.mutation.ResetExitCode()
	_u.mutation.SetExitCode(v)
	return _u
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableExitCode(v *int) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetExitCode(*v)
	}
	return _u
}

// AddExitCode adds value to the "exit_code" field.
func (_u *ScriptExecutionDetailUpdateOne) AddExitCode(v int) *ScriptExecutionDetailUpdateOne {
	_u.mutation.AddExitCode(v)
	return _u
}

// ClearExitCode clears the value of the "exit_code" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearExitCode() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearExitCode()
	return _u
}

// SetFullOutputPath sets the "full_output_path" field.
func (_u *ScriptExecutionDetailUpdateOne) SetFullOutputPath(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetFullOutputPath(v)
	return _u
}

// SetNillableFullOutputPath sets the "full_output_path" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableFullOutputPath(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetFullOutputPath(*v)
	}
	return _u
}

// ClearFullOutputPath clears the value of the "full_output_path" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearFullOutputPath() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearFullOutputPath()
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *ScriptExecutionDetailUpdateOne) SetTaskID(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableTaskID(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearTaskID() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearTaskID()
	return _u
}

// SetWorkerID sets the "worker_id" field.
func (_u *ScriptExecutionDetailUpdateOne) SetWorkerID(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetWorkerID(v)
	return _u
}

// SetNillableWorkerID sets the "worker_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableWorkerID(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetWorkerID(*v)
	}
	return _u
}

// ClearWorkerID clears the value of the "worker_id" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearWorkerID() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearWorkerID()
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *ScriptExecutionDetailUpdateOne) SetProxyID(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableProxyID(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearProxyID() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearProxyID()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ScriptExecutionDetailUpdateOne) SetErrorMessage(v string) *ScriptExecutionDetailUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableErrorMessage(v *string) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ScriptExecutionDetailUpdateOne) ClearErrorMessage() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *ScriptExecutionDetailUpdateOne) SetRetryCount(v uint32) *ScriptExecutionDetailUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *ScriptExecutionDetailUpdateOne) SetNillableRetryCount(v *uint32) *ScriptExecutionDetailUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *ScriptExecutionDetailUpdateOne) AddRetryCount(v int32) *ScriptExecutionDetailUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetExecution sets the "execution" edge to the ScriptExecution entity.
func (_u *ScriptExecutionDetailUpdateOne) SetExecution(v *ScriptExecution) *ScriptExecutionDetailUpdateOne {
	return _u.SetExecutionID(v.ID)
}

// Mutation returns the ScriptExecutionDetailMutation object of the builder.
func (_u *ScriptExecutionDetailUpdateOne) Mutation() *ScriptExecutionDetailMutation {
	return _u.mutation
}

// ClearExecution clears the "execution" edge to the ScriptExecution entity.
func (_u *ScriptExecutionDetailUpdateOne) ClearExecution() *ScriptExecutionDetailUpdateOne {
	_u.mutation.ClearExecution()
	return _u
}

// Where appends a list predicates to the ScriptExecutionDetailUpdate builder.
func (_u *ScriptExecutionDetailUpdateOne) Where(ps ...predicate.ScriptExecutionDetail) *ScriptExecutionDetailUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScriptExecutionDetailUpdateOne) Select(field string, fields ...string) *ScriptExecutionDetailUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScriptExecutionDetail entity.
func (_u *ScriptExecutionDetailUpdateOne) Save(ctx context.Context) (*ScriptExecutionDetail, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptExecutionDetailUpdateOne) SaveX(ctx context.Context) *ScriptExecutionDetail {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScriptExecutionDetailUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptExecutionDetailUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptExecutionDetailUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scriptexecutiondetail.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptExecutionDetailUpdateOne) check() error {
	if v, ok := _u.mutation.ExecutionID(); ok {
		if err := scriptexecutiondetail.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.execution_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiID(); ok {
		if err := scriptexecutiondetail.CiIDValidator(v); err != nil {
			return &ValidationError{Name: "ci_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.ci_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiName(); ok {
		if err := scriptexecutiondetail.CiNameValidator(v); err != nil {
			return &ValidationError{Name: "ci_name", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.ci_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CiIP(); ok {
		if err := scriptexecutiondetail.CiIPValidator(v); err != nil {
			return &ValidationError{Name: "ci_ip", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.ci_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecStatus(); ok {
		if err := scriptexecutiondetail.ExecStatusValidator(v); err != nil {
			return &ValidationError{Name: "exec_status", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.exec_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullOutputPath(); ok {
		if err := scriptexecutiondetail.FullOutputPathValidator(v); err != nil {
			return &ValidationError{Name: "full_output_path", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.full_output_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskID(); ok {
		if err := scriptexecutiondetail.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkerID(); ok {
		if err := scriptexecutiondetail.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.worker_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProxyID(); ok {
		if err := scriptexecutiondetail.ProxyIDValidator(v); err != nil {
			return &ValidationError{Name: "proxy_id", err: fmt.Errorf(`ent: validator failed for field "ScriptExecutionDetail.proxy_id": %w`, err)}
		}
	}
	if _u.mutation.ExecutionCleared() && len(_u.mutation.ExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScriptExecutionDetail.execution"`)
	}
	return nil
}

func (_u *ScriptExecutionDetailUpdateOne) sqlSave(ctx context.Context) (_node *ScriptExecutionDetail, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptexecutiondetail.Table, scriptexecutiondetail.Columns, sqlgraph.NewFieldSpec(scriptexecutiondetail.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScriptExecutionDetail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scriptexecutiondetail.FieldID)
		for _, f := range fields {
			if !scriptexecutiondetail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scriptexecutiondetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scriptexecutiondetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scriptexecutiondetail.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(scriptexecutiondetail.FieldStatus, field.TypeUint8, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldStatus, field.TypeUint8)
	}
	if value, ok := _u.mutation.CiID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCiID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CiName(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCiName, field.TypeString, value)
	}
	if _u.mutation.CiNameCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldCiName, field.TypeString)
	}
	if value, ok := _u.mutation.CiIP(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCiIP, field.TypeString, value)
	}
	if _u.mutation.CiIPCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldCiIP, field.TypeString)
	}
	if value, ok := _u.mutation.ExecStatus(); ok {
		_spec.SetField(scriptexecutiondetail.FieldExecStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(scriptexecutiondetail.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(scriptexecutiondetail.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(scriptexecutiondetail.FieldDurationMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(scriptexecutiondetail.FieldDurationMs, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Output(); ok {
		_spec.SetField(scriptexecutiondetail.FieldOutput, field.TypeString, value)
	}
	if _u.mutation.OutputCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldOutput, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorOutput(); ok {
		_spec.SetField(scriptexecutiondetail.FieldErrorOutput, field.TypeString, value)
	}
	if _u.mutation.ErrorOutputCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldErrorOutput, field.TypeString)
	}
	if value, ok := _u.mutation.ExitCode(); ok {
		_spec.SetField(scriptexecutiondetail.FieldExitCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExitCode(); ok {
		_spec.AddField(scriptexecutiondetail.FieldExitCode, field.TypeInt, value)
	}
	if _u.mutation.ExitCodeCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldExitCode, field.TypeInt)
	}
	if value, ok := _u.mutation.FullOutputPath(); ok {
		_spec.SetField(scriptexecutiondetail.FieldFullOutputPath, field.TypeString, value)
	}
	if _u.mutation.FullOutputPathCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldFullOutputPath, field.TypeString)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldTaskID, field.TypeString, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.WorkerID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldWorkerID, field.TypeString, value)
	}
	if _u.mutation.WorkerIDCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldWorkerID, field.TypeString)
	}
	if value, ok := _u.mutation.ProxyID(); ok {
		_spec.SetField(scriptexecutiondetail.FieldProxyID, field.TypeString, value)
	}
	if _u.mutation.ProxyIDCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldProxyID, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(scriptexecutiondetail.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(scriptexecutiondetail.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(scriptexecutiondetail.FieldRetryCount, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(scriptexecutiondetail.FieldRetryCount, field.TypeUint32, value)
	}
	if _u.mutation.ExecutionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptexecutiondetail.ExecutionTable,
			Columns: []string{scriptexecutiondetail.ExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptexecution.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptexecutiondetail.ExecutionTable,
			Columns: []string{scriptexecutiondetail.ExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptexecution.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScriptExecutionDetail{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptexecutiondetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
