// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/predicate"
	"github.com/coder-lulu/newbee-ops-rpc/ent/script"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptversion"
)

// ScriptVersionUpdate is the builder for updating ScriptVersion entities.
type ScriptVersionUpdate struct {
	config
	hooks    []Hook
	mutation *ScriptVersionMutation
}

// Where appends a list predicates to the ScriptVersionUpdate builder.
func (_u *ScriptVersionUpdate) Where(ps ...predicate.ScriptVersion) *ScriptVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptVersionUpdate) SetUpdatedAt(v time.Time) *ScriptVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *ScriptVersionUpdate) SetScriptID(v uint64) *ScriptVersionUpdate {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableScriptID(v *uint64) *ScriptVersionUpdate {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ScriptVersionUpdate) SetVersion(v string) *ScriptVersionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableVersion(v *string) *ScriptVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ScriptVersionUpdate) SetContent(v string) *ScriptVersionUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableContent(v *string) *ScriptVersionUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *ScriptVersionUpdate) SetParameters(v map[string]interface{}) *ScriptVersionUpdate {
	_u.mutation.SetParameters(v)
	return _u
}

// ClearParameters clears the value of the "parameters" field.
func (_u *ScriptVersionUpdate) ClearParameters() *ScriptVersionUpdate {
	_u.mutation.ClearParameters()
	return _u
}

// SetScriptType sets the "script_type" field.
func (_u *ScriptVersionUpdate) SetScriptType(v string) *ScriptVersionUpdate {
	_u.mutation.SetScriptType(v)
	return _u
}

// SetNillableScriptType sets the "script_type" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableScriptType(v *string) *ScriptVersionUpdate {
	if v != nil {
		_u.SetScriptType(*v)
	}
	return _u
}

// SetExecutor sets the "executor" field.
func (_u *ScriptVersionUpdate) SetExecutor(v string) *ScriptVersionUpdate {
	_u.mutation.SetExecutor(v)
	return _u
}

// SetNillableExecutor sets the "executor" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableExecutor(v *string) *ScriptVersionUpdate {
	if v != nil {
		_u.SetExecutor(*v)
	}
	return _u
}

// SetChangeLog sets the "change_log" field.
func (_u *ScriptVersionUpdate) SetChangeLog(v string) *ScriptVersionUpdate {
	_u.mutation.SetChangeLog(v)
	return _u
}

// SetNillableChangeLog sets the "change_log" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableChangeLog(v *string) *ScriptVersionUpdate {
	if v != nil {
		_u.SetChangeLog(*v)
	}
	return _u
}

// ClearChangeLog clears the value of the "change_log" field.
func (_u *ScriptVersionUpdate) ClearChangeLog() *ScriptVersionUpdate {
	_u.mutation.ClearChangeLog()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ScriptVersionUpdate) SetCreatedBy(v uint64) *ScriptVersionUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableCreatedBy(v *uint64) *ScriptVersionUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ScriptVersionUpdate) AddCreatedBy(v int64) *ScriptVersionUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *ScriptVersionUpdate) SetChecksum(v string) *ScriptVersionUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *ScriptVersionUpdate) SetNillableChecksum(v *string) *ScriptVersionUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetScript sets the "script" edge to the Script entity.
func (_u *ScriptVersionUpdate) SetScript(v *Script) *ScriptVersionUpdate {
	return _u.SetScriptID(v.ID)
}

// Mutation returns the ScriptVersionMutation object of the builder.
func (_u *ScriptVersionUpdate) Mutation() *ScriptVersionMutation {
	return _u.mutation
}

// ClearScript clears the "script" edge to the Script entity.
func (_u *ScriptVersionUpdate) ClearScript() *ScriptVersionUpdate {
	_u.mutation.ClearScript()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScriptVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScriptVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scriptversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptVersionUpdate) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := scriptversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScriptType(); ok {
		if err := scriptversion.ScriptTypeValidator(v); err != nil {
			return &ValidationError{Name: "script_type", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.script_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Executor(); ok {
		if err := scriptversion.ExecutorValidator(v); err != nil {
			return &ValidationError{Name: "executor", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.executor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := scriptversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.checksum": %w`, err)}
		}
	}
	if _u.mutation.ScriptCleared() && len(_u.mutation.ScriptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScriptVersion.script"`)
	}
	return nil
}

func (_u *ScriptVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptversion.Table, scriptversion.Columns, sqlgraph.NewFieldSpec(scriptversion.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scriptversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(scriptversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(scriptversion.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(scriptversion.FieldParameters, field.TypeJSON, value)
	}
	if _u.mutation.ParametersCleared() {
		_spec.ClearField(scriptversion.FieldParameters, field.TypeJSON)
	}
	if value, ok := _u.mutation.ScriptType(); ok {
		_spec.SetField(scriptversion.FieldScriptType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Executor(); ok {
		_spec.SetField(scriptversion.FieldExecutor, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangeLog(); ok {
		_spec.SetField(scriptversion.FieldChangeLog, field.TypeString, value)
	}
	if _u.mutation.ChangeLogCleared() {
		_spec.ClearField(scriptversion.FieldChangeLog, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(scriptversion.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(scriptversion.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(scriptversion.FieldChecksum, field.TypeString, value)
	}
	if _u.mutation.ScriptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptversion.ScriptTable,
			Columns: []string{scriptversion.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptversion.ScriptTable,
			Columns: []string{scriptversion.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScriptVersionUpdateOne is the builder for updating a single ScriptVersion entity.
type ScriptVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScriptVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptVersionUpdateOne) SetUpdatedAt(v time.Time) *ScriptVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *ScriptVersionUpdateOne) SetScriptID(v uint64) *ScriptVersionUpdateOne {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableScriptID(v *uint64) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ScriptVersionUpdateOne) SetVersion(v string) *ScriptVersionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableVersion(v *string) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ScriptVersionUpdateOne) SetContent(v string) *ScriptVersionUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableContent(v *string) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *ScriptVersionUpdateOne) SetParameters(v map[string]interface{}) *ScriptVersionUpdateOne {
	_u.mutation.SetParameters(v)
	return _u
}

// ClearParameters clears the value of the "parameters" field.
func (_u *ScriptVersionUpdateOne) ClearParameters() *ScriptVersionUpdateOne {
	_u.mutation.ClearParameters()
	return _u
}

// SetScriptType sets the "script_type" field.
func (_u *ScriptVersionUpdateOne) SetScriptType(v string) *ScriptVersionUpdateOne {
	_u.mutation.SetScriptType(v)
	return _u
}

// SetNillableScriptType sets the "script_type" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableScriptType(v *string) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetScriptType(*v)
	}
	return _u
}

// SetExecutor sets the "executor" field.
func (_u *ScriptVersionUpdateOne) SetExecutor(v string) *ScriptVersionUpdateOne {
	_u.mutation.SetExecutor(v)
	return _u
}

// SetNillableExecutor sets the "executor" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableExecutor(v *string) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetExecutor(*v)
	}
	return _u
}

// SetChangeLog sets the "change_log" field.
func (_u *ScriptVersionUpdateOne) SetChangeLog(v string) *ScriptVersionUpdateOne {
	_u.mutation.SetChangeLog(v)
	return _u
}

// SetNillableChangeLog sets the "change_log" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableChangeLog(v *string) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetChangeLog(*v)
	}
	return _u
}

// ClearChangeLog clears the value of the "change_log" field.
func (_u *ScriptVersionUpdateOne) ClearChangeLog() *ScriptVersionUpdateOne {
	_u.mutation.ClearChangeLog()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ScriptVersionUpdateOne) SetCreatedBy(v uint64) *ScriptVersionUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableCreatedBy(v *uint64) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ScriptVersionUpdateOne) AddCreatedBy(v int64) *ScriptVersionUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *ScriptVersionUpdateOne) SetChecksum(v string) *ScriptVersionUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *ScriptVersionUpdateOne) SetNillableChecksum(v *string) *ScriptVersionUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetScript sets the "script" edge to the Script entity.
func (_u *ScriptVersionUpdateOne) SetScript(v *Script) *ScriptVersionUpdateOne {
	return _u.SetScriptID(v.ID)
}

// Mutation returns the ScriptVersionMutation object of the builder.
func (_u *ScriptVersionUpdateOne) Mutation() *ScriptVersionMutation {
	return _u.mutation
}

// ClearScript clears the "script" edge to the Script entity.
func (_u *ScriptVersionUpdateOne) ClearScript() *ScriptVersionUpdateOne {
	_u.mutation.ClearScript()
	return _u
}

// Where appends a list predicates to the ScriptVersionUpdate builder.
func (_u *ScriptVersionUpdateOne) Where(ps ...predicate.ScriptVersion) *ScriptVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScriptVersionUpdateOne) Select(field string, fields ...string) *ScriptVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScriptVersion entity.
func (_u *ScriptVersionUpdateOne) Save(ctx context.Context) (*ScriptVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptVersionUpdateOne) SaveX(ctx context.Context) *ScriptVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScriptVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scriptversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Version(); ok {
		if err := scriptversion.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScriptType(); ok {
		if err := scriptversion.ScriptTypeValidator(v); err != nil {
			return &ValidationError{Name: "script_type", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.script_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Executor(); ok {
		if err := scriptversion.ExecutorValidator(v); err != nil {
			return &ValidationError{Name: "executor", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.executor": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checksum(); ok {
		if err := scriptversion.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "ScriptVersion.checksum": %w`, err)}
		}
	}
	if _u.mutation.ScriptCleared() && len(_u.mutation.ScriptIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScriptVersion.script"`)
	}
	return nil
}

func (_u *ScriptVersionUpdateOne) sqlSave(ctx context.Context) (_node *ScriptVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptversion.Table, scriptversion.Columns, sqlgraph.NewFieldSpec(scriptversion.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScriptVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scriptversion.FieldID)
		for _, f := range fields {
			if !scriptversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scriptversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scriptversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(scriptversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(scriptversion.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(scriptversion.FieldParameters, field.TypeJSON, value)
	}
	if _u.mutation.ParametersCleared() {
		_spec.ClearField(scriptversion.FieldParameters, field.TypeJSON)
	}
	if value, ok := _u.mutation.ScriptType(); ok {
		_spec.SetField(scriptversion.FieldScriptType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Executor(); ok {
		_spec.SetField(scriptversion.FieldExecutor, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangeLog(); ok {
		_spec.SetField(scriptversion.FieldChangeLog, field.TypeString, value)
	}
	if _u.mutation.ChangeLogCleared() {
		_spec.ClearField(scriptversion.FieldChangeLog, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(scriptversion.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(scriptversion.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(scriptversion.FieldChecksum, field.TypeString, value)
	}
	if _u.mutation.ScriptCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptversion.ScriptTable,
			Columns: []string{scriptversion.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScriptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptversion.ScriptTable,
			Columns: []string{scriptversion.ScriptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScriptVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
