// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/predicate"
	"github.com/coder-lulu/newbee-ops-rpc/ent/script"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecution"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecutiondetail"
)

// ScriptExecutionQuery is the builder for querying ScriptExecution entities.
type ScriptExecutionQuery struct {
	config
	ctx         *QueryContext
	order       []scriptexecution.OrderOption
	inters      []Interceptor
	predicates  []predicate.ScriptExecution
	withDetails *ScriptExecutionDetailQuery
	withScript  *ScriptQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ScriptExecutionQuery builder.
func (_q *ScriptExecutionQuery) Where(ps ...predicate.ScriptExecution) *ScriptExecutionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ScriptExecutionQuery) Limit(limit int) *ScriptExecutionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ScriptExecutionQuery) Offset(offset int) *ScriptExecutionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ScriptExecutionQuery) Unique(unique bool) *ScriptExecutionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ScriptExecutionQuery) Order(o ...scriptexecution.OrderOption) *ScriptExecutionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDetails chains the current query on the "details" edge.
func (_q *ScriptExecutionQuery) QueryDetails() *ScriptExecutionDetailQuery {
	query := (&ScriptExecutionDetailClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scriptexecution.Table, scriptexecution.FieldID, selector),
			sqlgraph.To(scriptexecutiondetail.Table, scriptexecutiondetail.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, scriptexecution.DetailsTable, scriptexecution.DetailsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScript chains the current query on the "script" edge.
func (_q *ScriptExecutionQuery) QueryScript() *ScriptQuery {
	query := (&ScriptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(scriptexecution.Table, scriptexecution.FieldID, selector),
			sqlgraph.To(script.Table, script.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, scriptexecution.ScriptTable, scriptexecution.ScriptColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ScriptExecution entity from the query.
// Returns a *NotFoundError when no ScriptExecution was found.
func (_q *ScriptExecutionQuery) First(ctx context.Context) (*ScriptExecution, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{scriptexecution.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ScriptExecutionQuery) FirstX(ctx context.Context) *ScriptExecution {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ScriptExecution ID from the query.
// Returns a *NotFoundError when no ScriptExecution ID was found.
func (_q *ScriptExecutionQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{scriptexecution.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ScriptExecutionQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ScriptExecution entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ScriptExecution entity is found.
// Returns a *NotFoundError when no ScriptExecution entities are found.
func (_q *ScriptExecutionQuery) Only(ctx context.Context) (*ScriptExecution, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{scriptexecution.Label}
	default:
		return nil, &NotSingularError{scriptexecution.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ScriptExecutionQuery) OnlyX(ctx context.Context) *ScriptExecution {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ScriptExecution ID in the query.
// Returns a *NotSingularError when more than one ScriptExecution ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ScriptExecutionQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{scriptexecution.Label}
	default:
		err = &NotSingularError{scriptexecution.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ScriptExecutionQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ScriptExecutions.
func (_q *ScriptExecutionQuery) All(ctx context.Context) ([]*ScriptExecution, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ScriptExecution, *ScriptExecutionQuery]()
	return withInterceptors[[]*ScriptExecution](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ScriptExecutionQuery) AllX(ctx context.Context) []*ScriptExecution {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ScriptExecution IDs.
func (_q *ScriptExecutionQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(scriptexecution.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ScriptExecutionQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ScriptExecutionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ScriptExecutionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ScriptExecutionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ScriptExecutionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ScriptExecutionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ScriptExecutionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ScriptExecutionQuery) Clone() *ScriptExecutionQuery {
	if _q == nil {
		return nil
	}
	return &ScriptExecutionQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]scriptexecution.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.ScriptExecution{}, _q.predicates...),
		withDetails: _q.withDetails.Clone(),
		withScript:  _q.withScript.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDetails tells the query-builder to eager-load the nodes that are connected to
// the "details" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScriptExecutionQuery) WithDetails(opts ...func(*ScriptExecutionDetailQuery)) *ScriptExecutionQuery {
	query := (&ScriptExecutionDetailClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDetails = query
	return _q
}

// WithScript tells the query-builder to eager-load the nodes that are connected to
// the "script" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ScriptExecutionQuery) WithScript(opts ...func(*ScriptQuery)) *ScriptExecutionQuery {
	query := (&ScriptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScript = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ScriptExecution.Query().
//		GroupBy(scriptexecution.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ScriptExecutionQuery) GroupBy(field string, fields ...string) *ScriptExecutionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ScriptExecutionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = scriptexecution.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.ScriptExecution.Query().
//		Select(scriptexecution.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ScriptExecutionQuery) Select(fields ...string) *ScriptExecutionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ScriptExecutionSelect{ScriptExecutionQuery: _q}
	sbuild.label = scriptexecution.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ScriptExecutionSelect configured with the given aggregations.
func (_q *ScriptExecutionQuery) Aggregate(fns ...AggregateFunc) *ScriptExecutionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ScriptExecutionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !scriptexecution.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ScriptExecutionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ScriptExecution, error) {
	var (
		nodes       = []*ScriptExecution{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withDetails != nil,
			_q.withScript != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ScriptExecution).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ScriptExecution{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDetails; query != nil {
		if err := _q.loadDetails(ctx, query, nodes,
			func(n *ScriptExecution) { n.Edges.Details = []*ScriptExecutionDetail{} },
			func(n *ScriptExecution, e *ScriptExecutionDetail) { n.Edges.Details = append(n.Edges.Details, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withScript; query != nil {
		if err := _q.loadScript(ctx, query, nodes, nil,
			func(n *ScriptExecution, e *Script) { n.Edges.Script = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ScriptExecutionQuery) loadDetails(ctx context.Context, query *ScriptExecutionDetailQuery, nodes []*ScriptExecution, init func(*ScriptExecution), assign func(*ScriptExecution, *ScriptExecutionDetail)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*ScriptExecution)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(scriptexecutiondetail.FieldExecutionID)
	}
	query.Where(predicate.ScriptExecutionDetail(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(scriptexecution.DetailsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ExecutionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "execution_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ScriptExecutionQuery) loadScript(ctx context.Context, query *ScriptQuery, nodes []*ScriptExecution, init func(*ScriptExecution), assign func(*ScriptExecution, *Script)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*ScriptExecution)
	for i := range nodes {
		fk := nodes[i].ScriptID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(script.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "script_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ScriptExecutionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ScriptExecutionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(scriptexecution.Table, scriptexecution.Columns, sqlgraph.NewFieldSpec(scriptexecution.FieldID, field.TypeUint64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scriptexecution.FieldID)
		for i := range fields {
			if fields[i] != scriptexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withScript != nil {
			_spec.Node.AddColumnOnce(scriptexecution.FieldScriptID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ScriptExecutionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(scriptexecution.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = scriptexecution.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ScriptExecutionGroupBy is the group-by builder for ScriptExecution entities.
type ScriptExecutionGroupBy struct {
	selector
	build *ScriptExecutionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ScriptExecutionGroupBy) Aggregate(fns ...AggregateFunc) *ScriptExecutionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ScriptExecutionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScriptExecutionQuery, *ScriptExecutionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ScriptExecutionGroupBy) sqlScan(ctx context.Context, root *ScriptExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ScriptExecutionSelect is the builder for selecting fields of ScriptExecution entities.
type ScriptExecutionSelect struct {
	*ScriptExecutionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ScriptExecutionSelect) Aggregate(fns ...AggregateFunc) *ScriptExecutionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ScriptExecutionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ScriptExecutionQuery, *ScriptExecutionSelect](ctx, _s.ScriptExecutionQuery, _s, _s.inters, v)
}

func (_s *ScriptExecutionSelect) sqlScan(ctx context.Context, root *ScriptExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
