// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecution"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecutiondetail"
)

// 脚本执行详情表
type ScriptExecutionDetail struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// 执行记录ID
	ExecutionID uint64 `json:"execution_id,omitempty"`
	// CI ID
	CiID string `json:"ci_id,omitempty"`
	// CI名称
	CiName string `json:"ci_name,omitempty"`
	// CI IP地址
	CiIP string `json:"ci_ip,omitempty"`
	// 执行状态：pending/running/success/failed/timeout/cancelled
	ExecStatus string `json:"exec_status,omitempty"`
	// 开始时间
	StartedAt *time.Time `json:"started_at,omitempty"`
	// 完成时间
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// 执行时长（毫秒）
	DurationMs uint64 `json:"duration_ms,omitempty"`
	// 标准输出（截断至10KB）
	Output string `json:"output,omitempty"`
	// 错误输出
	ErrorOutput string `json:"error_output,omitempty"`
	// 退出代码
	ExitCode *int `json:"exit_code,omitempty"`
	// 完整输出文件路径（S3/OSS）
	FullOutputPath string `json:"full_output_path,omitempty"`
	// 关联的Task ID
	TaskID string `json:"task_id,omitempty"`
	// 执行的Worker ID
	WorkerID string `json:"worker_id,omitempty"`
	// 使用的Proxy ID
	ProxyID string `json:"proxy_id,omitempty"`
	// 错误信息
	ErrorMessage string `json:"error_message,omitempty"`
	// 重试次数
	RetryCount uint32 `json:"retry_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScriptExecutionDetailQuery when eager-loading is set.
	Edges        ScriptExecutionDetailEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScriptExecutionDetailEdges holds the relations/edges for other nodes in the graph.
type ScriptExecutionDetailEdges struct {
	// Execution holds the value of the execution edge.
	Execution *ScriptExecution `json:"execution,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ExecutionOrErr returns the Execution value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScriptExecutionDetailEdges) ExecutionOrErr() (*ScriptExecution, error) {
	if e.Execution != nil {
		return e.Execution, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: scriptexecution.Label}
	}
	return nil, &NotLoadedError{edge: "execution"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScriptExecutionDetail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scriptexecutiondetail.FieldID, scriptexecutiondetail.FieldTenantID, scriptexecutiondetail.FieldStatus, scriptexecutiondetail.FieldExecutionID, scriptexecutiondetail.FieldDurationMs, scriptexecutiondetail.FieldExitCode, scriptexecutiondetail.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case scriptexecutiondetail.FieldCiID, scriptexecutiondetail.FieldCiName, scriptexecutiondetail.FieldCiIP, scriptexecutiondetail.FieldExecStatus, scriptexecutiondetail.FieldOutput, scriptexecutiondetail.FieldErrorOutput, scriptexecutiondetail.FieldFullOutputPath, scriptexecutiondetail.FieldTaskID, scriptexecutiondetail.FieldWorkerID, scriptexecutiondetail.FieldProxyID, scriptexecutiondetail.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case scriptexecutiondetail.FieldCreatedAt, scriptexecutiondetail.FieldUpdatedAt, scriptexecutiondetail.FieldStartedAt, scriptexecutiondetail.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScriptExecutionDetail fields.
func (_m *ScriptExecutionDetail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scriptexecutiondetail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case scriptexecutiondetail.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case scriptexecutiondetail.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case scriptexecutiondetail.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case scriptexecutiondetail.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case scriptexecutiondetail.FieldExecutionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field execution_id", values[i])
			} else if value.Valid {
				_m.ExecutionID = uint64(value.Int64)
			}
		case scriptexecutiondetail.FieldCiID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ci_id", values[i])
			} else if value.Valid {
				_m.CiID = value.String
			}
		case scriptexecutiondetail.FieldCiName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ci_name", values[i])
			} else if value.Valid {
				_m.CiName = value.String
			}
		case scriptexecutiondetail.FieldCiIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ci_ip", values[i])
			} else if value.Valid {
				_m.CiIP = value.String
			}
		case scriptexecutiondetail.FieldExecStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exec_status", values[i])
			} else if value.Valid {
				_m.ExecStatus = value.String
			}
		case scriptexecutiondetail.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case scriptexecutiondetail.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case scriptexecutiondetail.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = uint64(value.Int64)
			}
		case scriptexecutiondetail.FieldOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output", values[i])
			} else if value.Valid {
				_m.Output = value.String
			}
		case scriptexecutiondetail.FieldErrorOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_output", values[i])
			} else if value.Valid {
				_m.ErrorOutput = value.String
			}
		case scriptexecutiondetail.FieldExitCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exit_code", values[i])
			} else if value.Valid {
				_m.ExitCode = new(int)
				*_m.ExitCode = int(value.Int64)
			}
		case scriptexecutiondetail.FieldFullOutputPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_output_path", values[i])
			} else if value.Valid {
				_m.FullOutputPath = value.String
			}
		case scriptexecutiondetail.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case scriptexecutiondetail.FieldWorkerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field worker_id", values[i])
			} else if value.Valid {
				_m.WorkerID = value.String
			}
		case scriptexecutiondetail.FieldProxyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = value.String
			}
		case scriptexecutiondetail.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case scriptexecutiondetail.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScriptExecutionDetail.
// This includes values selected through modifiers, order, etc.
func (_m *ScriptExecutionDetail) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExecution queries the "execution" edge of the ScriptExecutionDetail entity.
func (_m *ScriptExecutionDetail) QueryExecution() *ScriptExecutionQuery {
	return NewScriptExecutionDetailClient(_m.config).QueryExecution(_m)
}

// Update returns a builder for updating this ScriptExecutionDetail.
// Note that you need to call ScriptExecutionDetail.Unwrap() before calling this method if this ScriptExecutionDetail
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScriptExecutionDetail) Update() *ScriptExecutionDetailUpdateOne {
	return NewScriptExecutionDetailClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScriptExecutionDetail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScriptExecutionDetail) Unwrap() *ScriptExecutionDetail {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScriptExecutionDetail is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScriptExecutionDetail) String() string {
	var builder strings.Builder
	builder.WriteString("ScriptExecutionDetail(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("execution_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutionID))
	builder.WriteString(", ")
	builder.WriteString("ci_id=")
	builder.WriteString(_m.CiID)
	builder.WriteString(", ")
	builder.WriteString("ci_name=")
	builder.WriteString(_m.CiName)
	builder.WriteString(", ")
	builder.WriteString("ci_ip=")
	builder.WriteString(_m.CiIP)
	builder.WriteString(", ")
	builder.WriteString("exec_status=")
	builder.WriteString(_m.ExecStatus)
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("output=")
	builder.WriteString(_m.Output)
	builder.WriteString(", ")
	builder.WriteString("error_output=")
	builder.WriteString(_m.ErrorOutput)
	builder.WriteString(", ")
	if v := _m.ExitCode; v != nil {
		builder.WriteString("exit_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("full_output_path=")
	builder.WriteString(_m.FullOutputPath)
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("worker_id=")
	builder.WriteString(_m.WorkerID)
	builder.WriteString(", ")
	builder.WriteString("proxy_id=")
	builder.WriteString(_m.ProxyID)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteByte(')')
	return builder.String()
}

// ScriptExecutionDetails is a parsable slice of ScriptExecutionDetail.
type ScriptExecutionDetails []*ScriptExecutionDetail
