// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/script"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptcategory"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecution"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptversion"
)

// ScriptCreate is the builder for creating a Script entity.
type ScriptCreate struct {
	config
	mutation *ScriptMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScriptCreate) SetCreatedAt(v time.Time) *ScriptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableCreatedAt(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScriptCreate) SetUpdatedAt(v time.Time) *ScriptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableUpdatedAt(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ScriptCreate) SetTenantID(v uint64) *ScriptCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableTenantID(v *uint64) *ScriptCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *ScriptCreate) SetDepartmentID(v uint64) *ScriptCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDepartmentID(v *uint64) *ScriptCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ScriptCreate) SetStatus(v uint8) *ScriptCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableStatus(v *uint8) *ScriptCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ScriptCreate) SetName(v string) *ScriptCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *ScriptCreate) SetCode(v string) *ScriptCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ScriptCreate) SetDescription(v string) *ScriptCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDescription(v *string) *ScriptCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *ScriptCreate) SetCategoryID(v uint64) *ScriptCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableCategoryID(v *uint64) *ScriptCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *ScriptCreate) SetTags(v []string) *ScriptCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetScriptType sets the "script_type" field.
func (_c *ScriptCreate) SetScriptType(v string) *ScriptCreate {
	_c.mutation.SetScriptType(v)
	return _c
}

// SetExecutor sets the "executor" field.
func (_c *ScriptCreate) SetExecutor(v string) *ScriptCreate {
	_c.mutation.SetExecutor(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ScriptCreate) SetContent(v string) *ScriptCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetIsTemplate sets the "is_template" field.
func (_c *ScriptCreate) SetIsTemplate(v bool) *ScriptCreate {
	_c.mutation.SetIsTemplate(v)
	return _c
}

// SetNillableIsTemplate sets the "is_template" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableIsTemplate(v *bool) *ScriptCreate {
	if v != nil {
		_c.SetIsTemplate(*v)
	}
	return _c
}

// SetTemplateEngine sets the "template_engine" field.
func (_c *ScriptCreate) SetTemplateEngine(v string) *ScriptCreate {
	_c.mutation.SetTemplateEngine(v)
	return _c
}

// SetNillableTemplateEngine sets the "template_engine" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableTemplateEngine(v *string) *ScriptCreate {
	if v != nil {
		_c.SetTemplateEngine(*v)
	}
	return _c
}

// SetParameters sets the "parameters" field.
func (_c *ScriptCreate) SetParameters(v map[string]interface{}) *ScriptCreate {
	_c.mutation.SetParameters(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ScriptCreate) SetVersion(v string) *ScriptCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableVersion(v *string) *ScriptCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetBaseVersionID sets the "base_version_id" field.
func (_c *ScriptCreate) SetBaseVersionID(v uint64) *ScriptCreate {
	_c.mutation.SetBaseVersionID(v)
	return _c
}

// SetNillableBaseVersionID sets the "base_version_id" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableBaseVersionID(v *uint64) *ScriptCreate {
	if v != nil {
		_c.SetBaseVersionID(*v)
	}
	return _c
}

// SetIsLatest sets the "is_latest" field.
func (_c *ScriptCreate) SetIsLatest(v bool) *ScriptCreate {
	_c.mutation.SetIsLatest(v)
	return _c
}

// SetNillableIsLatest sets the "is_latest" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableIsLatest(v *bool) *ScriptCreate {
	if v != nil {
		_c.SetIsLatest(*v)
	}
	return _c
}

// SetTargetCiTypes sets the "target_ci_types" field.
func (_c *ScriptCreate) SetTargetCiTypes(v []string) *ScriptCreate {
	_c.mutation.SetTargetCiTypes(v)
	return _c
}

// SetTargetOsTypes sets the "target_os_types" field.
func (_c *ScriptCreate) SetTargetOsTypes(v []string) *ScriptCreate {
	_c.mutation.SetTargetOsTypes(v)
	return _c
}

// SetTargetSelector sets the "target_selector" field.
func (_c *ScriptCreate) SetTargetSelector(v map[string]interface{}) *ScriptCreate {
	_c.mutation.SetTargetSelector(v)
	return _c
}

// SetCredentialRef sets the "credential_ref" field.
func (_c *ScriptCreate) SetCredentialRef(v string) *ScriptCreate {
	_c.mutation.SetCredentialRef(v)
	return _c
}

// SetNillableCredentialRef sets the "credential_ref" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableCredentialRef(v *string) *ScriptCreate {
	if v != nil {
		_c.SetCredentialRef(*v)
	}
	return _c
}

// SetRequiredCapabilities sets the "required_capabilities" field.
func (_c *ScriptCreate) SetRequiredCapabilities(v []string) *ScriptCreate {
	_c.mutation.SetRequiredCapabilities(v)
	return _c
}

// SetDefaultTimeout sets the "default_timeout" field.
func (_c *ScriptCreate) SetDefaultTimeout(v uint32) *ScriptCreate {
	_c.mutation.SetDefaultTimeout(v)
	return _c
}

// SetNillableDefaultTimeout sets the "default_timeout" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDefaultTimeout(v *uint32) *ScriptCreate {
	if v != nil {
		_c.SetDefaultTimeout(*v)
	}
	return _c
}

// SetDefaultWorkdir sets the "default_workdir" field.
func (_c *ScriptCreate) SetDefaultWorkdir(v string) *ScriptCreate {
	_c.mutation.SetDefaultWorkdir(v)
	return _c
}

// SetNillableDefaultWorkdir sets the "default_workdir" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDefaultWorkdir(v *string) *ScriptCreate {
	if v != nil {
		_c.SetDefaultWorkdir(*v)
	}
	return _c
}

// SetDefaultEnv sets the "default_env" field.
func (_c *ScriptCreate) SetDefaultEnv(v map[string]string) *ScriptCreate {
	_c.mutation.SetDefaultEnv(v)
	return _c
}

// SetRequireConfirmation sets the "require_confirmation" field.
func (_c *ScriptCreate) SetRequireConfirmation(v bool) *ScriptCreate {
	_c.mutation.SetRequireConfirmation(v)
	return _c
}

// SetNillableRequireConfirmation sets the "require_confirmation" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableRequireConfirmation(v *bool) *ScriptCreate {
	if v != nil {
		_c.SetRequireConfirmation(*v)
	}
	return _c
}

// SetRiskLevel sets the "risk_level" field.
func (_c *ScriptCreate) SetRiskLevel(v string) *ScriptCreate {
	_c.mutation.SetRiskLevel(v)
	return _c
}

// SetNillableRiskLevel sets the "risk_level" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableRiskLevel(v *string) *ScriptCreate {
	if v != nil {
		_c.SetRiskLevel(*v)
	}
	return _c
}

// SetSchedulable sets the "schedulable" field.
func (_c *ScriptCreate) SetSchedulable(v bool) *ScriptCreate {
	_c.mutation.SetSchedulable(v)
	return _c
}

// SetNillableSchedulable sets the "schedulable" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableSchedulable(v *bool) *ScriptCreate {
	if v != nil {
		_c.SetSchedulable(*v)
	}
	return _c
}

// SetDefaultSchedule sets the "default_schedule" field.
func (_c *ScriptCreate) SetDefaultSchedule(v string) *ScriptCreate {
	_c.mutation.SetDefaultSchedule(v)
	return _c
}

// SetNillableDefaultSchedule sets the "default_schedule" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDefaultSchedule(v *string) *ScriptCreate {
	if v != nil {
		_c.SetDefaultSchedule(*v)
	}
	return _c
}

// SetExecutionCount sets the "execution_count" field.
func (_c *ScriptCreate) SetExecutionCount(v uint64) *ScriptCreate {
	_c.mutation.SetExecutionCount(v)
	return _c
}

// SetNillableExecutionCount sets the "execution_count" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableExecutionCount(v *uint64) *ScriptCreate {
	if v != nil {
		_c.SetExecutionCount(*v)
	}
	return _c
}

// SetSuccessCount sets the "success_count" field.
func (_c *ScriptCreate) SetSuccessCount(v uint64) *ScriptCreate {
	_c.mutation.SetSuccessCount(v)
	return _c
}

// SetNillableSuccessCount sets the "success_count" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableSuccessCount(v *uint64) *ScriptCreate {
	if v != nil {
		_c.SetSuccessCount(*v)
	}
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *ScriptCreate) SetFailureCount(v uint64) *ScriptCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetNillableFailureCount sets the "failure_count" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableFailureCount(v *uint64) *ScriptCreate {
	if v != nil {
		_c.SetFailureCount(*v)
	}
	return _c
}

// SetLastExecutedAt sets the "last_executed_at" field.
func (_c *ScriptCreate) SetLastExecutedAt(v int64) *ScriptCreate {
	_c.mutation.SetLastExecutedAt(v)
	return _c
}

// SetNillableLastExecutedAt sets the "last_executed_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableLastExecutedAt(v *int64) *ScriptCreate {
	if v != nil {
		_c.SetLastExecutedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScriptCreate) SetID(v uint64) *ScriptCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCategory sets the "category" edge to the ScriptCategory entity.
func (_c *ScriptCreate) SetCategory(v *ScriptCategory) *ScriptCreate {
	return _c.SetCategoryID(v.ID)
}

// AddVersionIDs adds the "versions" edge to the ScriptVersion entity by IDs.
func (_c *ScriptCreate) AddVersionIDs(ids ...uint64) *ScriptCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the ScriptVersion entity.
func (_c *ScriptCreate) AddVersions(v ...*ScriptVersion) *ScriptCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// AddExecutionIDs adds the "executions" edge to the ScriptExecution entity by IDs.
func (_c *ScriptCreate) AddExecutionIDs(ids ...uint64) *ScriptCreate {
	_c.mutation.AddExecutionIDs(ids...)
	return _c
}

// AddExecutions adds the "executions" edges to the ScriptExecution entity.
func (_c *ScriptCreate) AddExecutions(v ...*ScriptExecution) *ScriptCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExecutionIDs(ids...)
}

// Mutation returns the ScriptMutation object of the builder.
func (_c *ScriptCreate) Mutation() *ScriptMutation {
	return _c.mutation
}

// Save creates the Script in the database.
func (_c *ScriptCreate) Save(ctx context.Context) (*Script, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScriptCreate) SaveX(ctx context.Context) *Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScriptCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := script.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := script.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := script.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := script.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsTemplate(); !ok {
		v := script.DefaultIsTemplate
		_c.mutation.SetIsTemplate(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := script.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.IsLatest(); !ok {
		v := script.DefaultIsLatest
		_c.mutation.SetIsLatest(v)
	}
	if _, ok := _c.mutation.DefaultTimeout(); !ok {
		v := script.DefaultDefaultTimeout
		_c.mutation.SetDefaultTimeout(v)
	}
	if _, ok := _c.mutation.RequireConfirmation(); !ok {
		v := script.DefaultRequireConfirmation
		_c.mutation.SetRequireConfirmation(v)
	}
	if _, ok := _c.mutation.RiskLevel(); !ok {
		v := script.DefaultRiskLevel
		_c.mutation.SetRiskLevel(v)
	}
	if _, ok := _c.mutation.Schedulable(); !ok {
		v := script.DefaultSchedulable
		_c.mutation.SetSchedulable(v)
	}
	if _, ok := _c.mutation.ExecutionCount(); !ok {
		v := script.DefaultExecutionCount
		_c.mutation.SetExecutionCount(v)
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		v := script.DefaultSuccessCount
		_c.mutation.SetSuccessCount(v)
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		v := script.DefaultFailureCount
		_c.mutation.SetFailureCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScriptCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Script.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Script.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Script.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Script.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Script.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := script.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Script.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := script.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Script.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScriptType(); !ok {
		return &ValidationError{Name: "script_type", err: errors.New(`ent: missing required field "Script.script_type"`)}
	}
	if v, ok := _c.mutation.ScriptType(); ok {
		if err := script.ScriptTypeValidator(v); err != nil {
			return &ValidationError{Name: "script_type", err: fmt.Errorf(`ent: validator failed for field "Script.script_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Executor(); !ok {
		return &ValidationError{Name: "executor", err: errors.New(`ent: missing required field "Script.executor"`)}
	}
	if v, ok := _c.mutation.Executor(); ok {
		if err := script.ExecutorValidator(v); err != nil {
			return &ValidationError{Name: "executor", err: fmt.Errorf(`ent: validator failed for field "Script.executor": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Script.content"`)}
	}
	if _, ok := _c.mutation.IsTemplate(); !ok {
		return &ValidationError{Name: "is_template", err: errors.New(`ent: missing required field "Script.is_template"`)}
	}
	if v, ok := _c.mutation.TemplateEngine(); ok {
		if err := script.TemplateEngineValidator(v); err != nil {
			return &ValidationError{Name: "template_engine", err: fmt.Errorf(`ent: validator failed for field "Script.template_engine": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Script.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := script.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Script.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsLatest(); !ok {
		return &ValidationError{Name: "is_latest", err: errors.New(`ent: missing required field "Script.is_latest"`)}
	}
	if v, ok := _c.mutation.CredentialRef(); ok {
		if err := script.CredentialRefValidator(v); err != nil {
			return &ValidationError{Name: "credential_ref", err: fmt.Errorf(`ent: validator failed for field "Script.credential_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultTimeout(); !ok {
		return &ValidationError{Name: "default_timeout", err: errors.New(`ent: missing required field "Script.default_timeout"`)}
	}
	if v, ok := _c.mutation.DefaultWorkdir(); ok {
		if err := script.DefaultWorkdirValidator(v); err != nil {
			return &ValidationError{Name: "default_workdir", err: fmt.Errorf(`ent: validator failed for field "Script.default_workdir": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequireConfirmation(); !ok {
		return &ValidationError{Name: "require_confirmation", err: errors.New(`ent: missing required field "Script.require_confirmation"`)}
	}
	if _, ok := _c.mutation.RiskLevel(); !ok {
		return &ValidationError{Name: "risk_level", err: errors.New(`ent: missing required field "Script.risk_level"`)}
	}
	if v, ok := _c.mutation.RiskLevel(); ok {
		if err := script.RiskLevelValidator(v); err != nil {
			return &ValidationError{Name: "risk_level", err: fmt.Errorf(`ent: validator failed for field "Script.risk_level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Schedulable(); !ok {
		return &ValidationError{Name: "schedulable", err: errors.New(`ent: missing required field "Script.schedulable"`)}
	}
	if v, ok := _c.mutation.DefaultSchedule(); ok {
		if err := script.DefaultScheduleValidator(v); err != nil {
			return &ValidationError{Name: "default_schedule", err: fmt.Errorf(`ent: validator failed for field "Script.default_schedule": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionCount(); !ok {
		return &ValidationError{Name: "execution_count", err: errors.New(`ent: missing required field "Script.execution_count"`)}
	}
	if _, ok := _c.mutation.SuccessCount(); !ok {
		return &ValidationError{Name: "success_count", err: errors.New(`ent: missing required field "Script.success_count"`)}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "Script.failure_count"`)}
	}
	return nil
}

func (_c *ScriptCreate) sqlSave(ctx context.Context) (*Script, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScriptCreate) createSpec() (*Script, *sqlgraph.CreateSpec) {
	var (
		_node = &Script{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(script.Table, sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(script.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(script.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(script.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.DepartmentID(); ok {
		_spec.SetField(script.FieldDepartmentID, field.TypeUint64, value)
		_node.DepartmentID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(script.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(script.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(script.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(script.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.ScriptType(); ok {
		_spec.SetField(script.FieldScriptType, field.TypeString, value)
		_node.ScriptType = value
	}
	if value, ok := _c.mutation.Executor(); ok {
		_spec.SetField(script.FieldExecutor, field.TypeString, value)
		_node.Executor = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(script.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.IsTemplate(); ok {
		_spec.SetField(script.FieldIsTemplate, field.TypeBool, value)
		_node.IsTemplate = value
	}
	if value, ok := _c.mutation.TemplateEngine(); ok {
		_spec.SetField(script.FieldTemplateEngine, field.TypeString, value)
		_node.TemplateEngine = value
	}
	if value, ok := _c.mutation.Parameters(); ok {
		_spec.SetField(script.FieldParameters, field.TypeJSON, value)
		_node.Parameters = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(script.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.BaseVersionID(); ok {
		_spec.SetField(script.FieldBaseVersionID, field.TypeUint64, value)
		_node.BaseVersionID = value
	}
	if value, ok := _c.mutation.IsLatest(); ok {
		_spec.SetField(script.FieldIsLatest, field.TypeBool, value)
		_node.IsLatest = value
	}
	if value, ok := _c.mutation.TargetCiTypes(); ok {
		_spec.SetField(script.FieldTargetCiTypes, field.TypeJSON, value)
		_node.TargetCiTypes = value
	}
	if value, ok := _c.mutation.TargetOsTypes(); ok {
		_spec.SetField(script.FieldTargetOsTypes, field.TypeJSON, value)
		_node.TargetOsTypes = value
	}
	if value, ok := _c.mutation.TargetSelector(); ok {
		_spec.SetField(script.FieldTargetSelector, field.TypeJSON, value)
		_node.TargetSelector = value
	}
	if value, ok := _c.mutation.CredentialRef(); ok {
		_spec.SetField(script.FieldCredentialRef, field.TypeString, value)
		_node.CredentialRef = value
	}
	if value, ok := _c.mutation.RequiredCapabilities(); ok {
		_spec.SetField(script.FieldRequiredCapabilities, field.TypeJSON, value)
		_node.RequiredCapabilities = value
	}
	if value, ok := _c.mutation.DefaultTimeout(); ok {
		_spec.SetField(script.FieldDefaultTimeout, field.TypeUint32, value)
		_node.DefaultTimeout = value
	}
	if value, ok := _c.mutation.DefaultWorkdir(); ok {
		_spec.SetField(script.FieldDefaultWorkdir, field.TypeString, value)
		_node.DefaultWorkdir = value
	}
	if value, ok := _c.mutation.DefaultEnv(); ok {
		_spec.SetField(script.FieldDefaultEnv, field.TypeJSON, value)
		_node.DefaultEnv = value
	}
	if value, ok := _c.mutation.RequireConfirmation(); ok {
		_spec.SetField(script.FieldRequireConfirmation, field.TypeBool, value)
		_node.RequireConfirmation = value
	}
	if value, ok := _c.mutation.RiskLevel(); ok {
		_spec.SetField(script.FieldRiskLevel, field.TypeString, value)
		_node.RiskLevel = value
	}
	if value, ok := _c.mutation.Schedulable(); ok {
		_spec.SetField(script.FieldSchedulable, field.TypeBool, value)
		_node.Schedulable = value
	}
	if value, ok := _c.mutation.DefaultSchedule(); ok {
		_spec.SetField(script.FieldDefaultSchedule, field.TypeString, value)
		_node.DefaultSchedule = value
	}
	if value, ok := _c.mutation.ExecutionCount(); ok {
		_spec.SetField(script.FieldExecutionCount, field.TypeUint64, value)
		_node.ExecutionCount = value
	}
	if value, ok := _c.mutation.SuccessCount(); ok {
		_spec.SetField(script.FieldSuccessCount, field.TypeUint64, value)
		_node.SuccessCount = value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(script.FieldFailureCount, field.TypeUint64, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.LastExecutedAt(); ok {
		_spec.SetField(script.FieldLastExecutedAt, field.TypeInt64, value)
		_node.LastExecutedAt = value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   script.CategoryTable,
			Columns: []string{script.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.VersionsTable,
			Columns: []string{script.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptversion.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   script.ExecutionsTable,
			Columns: []string{script.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptexecution.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScriptCreateBulk is the builder for creating many Script entities in bulk.
type ScriptCreateBulk struct {
	config
	err      error
	builders []*ScriptCreate
}

// Save creates the Script entities in the database.
func (_c *ScriptCreateBulk) Save(ctx context.Context) ([]*Script, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Script, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScriptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScriptCreateBulk) SaveX(ctx context.Context) []*Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
