// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-ops-rpc/ent/script"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptversion"
)

// ScriptVersion is the model entity for the ScriptVersion schema.
type ScriptVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// 脚本ID
	ScriptID uint64 `json:"script_id,omitempty"`
	// 版本号
	Version string `json:"version,omitempty"`
	// 脚本内容快照
	Content string `json:"content,omitempty"`
	// 参数定义快照（JSON Schema格式）
	Parameters map[string]interface{} `json:"parameters,omitempty"`
	// 脚本类型快照
	ScriptType string `json:"script_type,omitempty"`
	// 执行器类型快照
	Executor string `json:"executor,omitempty"`
	// 变更日志
	ChangeLog string `json:"change_log,omitempty"`
	// 创建者用户ID
	CreatedBy uint64 `json:"created_by,omitempty"`
	// 内容校验和（SHA256）
	Checksum string `json:"checksum,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScriptVersionQuery when eager-loading is set.
	Edges        ScriptVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScriptVersionEdges holds the relations/edges for other nodes in the graph.
type ScriptVersionEdges struct {
	// Script holds the value of the script edge.
	Script *Script `json:"script,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ScriptOrErr returns the Script value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScriptVersionEdges) ScriptOrErr() (*Script, error) {
	if e.Script != nil {
		return e.Script, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: script.Label}
	}
	return nil, &NotLoadedError{edge: "script"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScriptVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scriptversion.FieldParameters:
			values[i] = new([]byte)
		case scriptversion.FieldID, scriptversion.FieldTenantID, scriptversion.FieldScriptID, scriptversion.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case scriptversion.FieldVersion, scriptversion.FieldContent, scriptversion.FieldScriptType, scriptversion.FieldExecutor, scriptversion.FieldChangeLog, scriptversion.FieldChecksum:
			values[i] = new(sql.NullString)
		case scriptversion.FieldCreatedAt, scriptversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScriptVersion fields.
func (_m *ScriptVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scriptversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case scriptversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case scriptversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case scriptversion.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case scriptversion.FieldScriptID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field script_id", values[i])
			} else if value.Valid {
				_m.ScriptID = uint64(value.Int64)
			}
		case scriptversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case scriptversion.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case scriptversion.FieldParameters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parameters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Parameters); err != nil {
					return fmt.Errorf("unmarshal field parameters: %w", err)
				}
			}
		case scriptversion.FieldScriptType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field script_type", values[i])
			} else if value.Valid {
				_m.ScriptType = value.String
			}
		case scriptversion.FieldExecutor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field executor", values[i])
			} else if value.Valid {
				_m.Executor = value.String
			}
		case scriptversion.FieldChangeLog:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field change_log", values[i])
			} else if value.Valid {
				_m.ChangeLog = value.String
			}
		case scriptversion.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = uint64(value.Int64)
			}
		case scriptversion.FieldChecksum:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value.Valid {
				_m.Checksum = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScriptVersion.
// This includes values selected through modifiers, order, etc.
func (_m *ScriptVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryScript queries the "script" edge of the ScriptVersion entity.
func (_m *ScriptVersion) QueryScript() *ScriptQuery {
	return NewScriptVersionClient(_m.config).QueryScript(_m)
}

// Update returns a builder for updating this ScriptVersion.
// Note that you need to call ScriptVersion.Unwrap() before calling this method if this ScriptVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScriptVersion) Update() *ScriptVersionUpdateOne {
	return NewScriptVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScriptVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScriptVersion) Unwrap() *ScriptVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScriptVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScriptVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ScriptVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("script_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScriptID))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("parameters=")
	builder.WriteString(fmt.Sprintf("%v", _m.Parameters))
	builder.WriteString(", ")
	builder.WriteString("script_type=")
	builder.WriteString(_m.ScriptType)
	builder.WriteString(", ")
	builder.WriteString("executor=")
	builder.WriteString(_m.Executor)
	builder.WriteString(", ")
	builder.WriteString("change_log=")
	builder.WriteString(_m.ChangeLog)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(_m.Checksum)
	builder.WriteByte(')')
	return builder.String()
}

// ScriptVersions is a parsable slice of ScriptVersion.
type ScriptVersions []*ScriptVersion
