// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/coder-lulu/newbee-ops-rpc/ent/script"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptexecution"
)

// 脚本执行记录表
type ScriptExecution struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Create Time | 创建日期
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Update Time | 修改日期
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Tenant ID | 租户 ID
	TenantID uint64 `json:"tenant_id,omitempty"`
	// Status 1: normal 2: ban | 状态 1 正常 2 禁用
	Status uint8 `json:"status,omitempty"`
	// 脚本ID
	ScriptID uint64 `json:"script_id,omitempty"`
	// 执行ID（UUID）
	ExecutionID string `json:"execution_id,omitempty"`
	// 执行用户ID
	ExecutorUserID uint64 `json:"executor_user_id,omitempty"`
	// 触发类型：manual/schedule/event/api
	TriggerType string `json:"trigger_type,omitempty"`
	// 目标CI ID列表
	TargetCiIds []string `json:"target_ci_ids,omitempty"`
	// 目标数量
	TargetCount uint32 `json:"target_count,omitempty"`
	// 渲染后的参数（JSON）
	Parameters string `json:"parameters,omitempty"`
	// 用户输入的原始参数（JSON）
	RawParameters string `json:"raw_parameters,omitempty"`
	// 执行状态：pending/running/success/partial_success/failed/timeout/cancelled
	ExecutionStatus string `json:"execution_status,omitempty"`
	// 开始时间
	StartedAt *time.Time `json:"started_at,omitempty"`
	// 完成时间
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// 执行时长（毫秒）
	DurationMs uint64 `json:"duration_ms,omitempty"`
	// 成功数量
	SuccessCount uint32 `json:"success_count,omitempty"`
	// 失败数量
	FailureCount uint32 `json:"failure_count,omitempty"`
	// 超时数量
	TimeoutCount uint32 `json:"timeout_count,omitempty"`
	// 关联的Task ID
	TaskID string `json:"task_id,omitempty"`
	// 错误信息
	ErrorMessage string `json:"error_message,omitempty"`
	// 执行日志摘要
	ExecutionLog string `json:"execution_log,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScriptExecutionQuery when eager-loading is set.
	Edges        ScriptExecutionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScriptExecutionEdges holds the relations/edges for other nodes in the graph.
type ScriptExecutionEdges struct {
	// 执行详情
	Details []*ScriptExecutionDetail `json:"details,omitempty"`
	// Script holds the value of the script edge.
	Script *Script `json:"script,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DetailsOrErr returns the Details value or an error if the edge
// was not loaded in eager-loading.
func (e ScriptExecutionEdges) DetailsOrErr() ([]*ScriptExecutionDetail, error) {
	if e.loadedTypes[0] {
		return e.Details, nil
	}
	return nil, &NotLoadedError{edge: "details"}
}

// ScriptOrErr returns the Script value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScriptExecutionEdges) ScriptOrErr() (*Script, error) {
	if e.Script != nil {
		return e.Script, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: script.Label}
	}
	return nil, &NotLoadedError{edge: "script"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScriptExecution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scriptexecution.FieldTargetCiIds:
			values[i] = new([]byte)
		case scriptexecution.FieldID, scriptexecution.FieldTenantID, scriptexecution.FieldStatus, scriptexecution.FieldScriptID, scriptexecution.FieldExecutorUserID, scriptexecution.FieldTargetCount, scriptexecution.FieldDurationMs, scriptexecution.FieldSuccessCount, scriptexecution.FieldFailureCount, scriptexecution.FieldTimeoutCount:
			values[i] = new(sql.NullInt64)
		case scriptexecution.FieldExecutionID, scriptexecution.FieldTriggerType, scriptexecution.FieldParameters, scriptexecution.FieldRawParameters, scriptexecution.FieldExecutionStatus, scriptexecution.FieldTaskID, scriptexecution.FieldErrorMessage, scriptexecution.FieldExecutionLog:
			values[i] = new(sql.NullString)
		case scriptexecution.FieldCreatedAt, scriptexecution.FieldUpdatedAt, scriptexecution.FieldStartedAt, scriptexecution.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScriptExecution fields.
func (_m *ScriptExecution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scriptexecution.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case scriptexecution.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case scriptexecution.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case scriptexecution.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint64(value.Int64)
			}
		case scriptexecution.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case scriptexecution.FieldScriptID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field script_id", values[i])
			} else if value.Valid {
				_m.ScriptID = uint64(value.Int64)
			}
		case scriptexecution.FieldExecutionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_id", values[i])
			} else if value.Valid {
				_m.ExecutionID = value.String
			}
		case scriptexecution.FieldExecutorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field executor_user_id", values[i])
			} else if value.Valid {
				_m.ExecutorUserID = uint64(value.Int64)
			}
		case scriptexecution.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = value.String
			}
		case scriptexecution.FieldTargetCiIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field target_ci_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TargetCiIds); err != nil {
					return fmt.Errorf("unmarshal field target_ci_ids: %w", err)
				}
			}
		case scriptexecution.FieldTargetCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_count", values[i])
			} else if value.Valid {
				_m.TargetCount = uint32(value.Int64)
			}
		case scriptexecution.FieldParameters:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parameters", values[i])
			} else if value.Valid {
				_m.Parameters = value.String
			}
		case scriptexecution.FieldRawParameters:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_parameters", values[i])
			} else if value.Valid {
				_m.RawParameters = value.String
			}
		case scriptexecution.FieldExecutionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_status", values[i])
			} else if value.Valid {
				_m.ExecutionStatus = value.String
			}
		case scriptexecution.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case scriptexecution.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case scriptexecution.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = uint64(value.Int64)
			}
		case scriptexecution.FieldSuccessCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_count", values[i])
			} else if value.Valid {
				_m.SuccessCount = uint32(value.Int64)
			}
		case scriptexecution.FieldFailureCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failure_count", values[i])
			} else if value.Valid {
				_m.FailureCount = uint32(value.Int64)
			}
		case scriptexecution.FieldTimeoutCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_count", values[i])
			} else if value.Valid {
				_m.TimeoutCount = uint32(value.Int64)
			}
		case scriptexecution.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case scriptexecution.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case scriptexecution.FieldExecutionLog:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_log", values[i])
			} else if value.Valid {
				_m.ExecutionLog = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScriptExecution.
// This includes values selected through modifiers, order, etc.
func (_m *ScriptExecution) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDetails queries the "details" edge of the ScriptExecution entity.
func (_m *ScriptExecution) QueryDetails() *ScriptExecutionDetailQuery {
	return NewScriptExecutionClient(_m.config).QueryDetails(_m)
}

// QueryScript queries the "script" edge of the ScriptExecution entity.
func (_m *ScriptExecution) QueryScript() *ScriptQuery {
	return NewScriptExecutionClient(_m.config).QueryScript(_m)
}

// Update returns a builder for updating this ScriptExecution.
// Note that you need to call ScriptExecution.Unwrap() before calling this method if this ScriptExecution
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScriptExecution) Update() *ScriptExecutionUpdateOne {
	return NewScriptExecutionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScriptExecution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScriptExecution) Unwrap() *ScriptExecution {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScriptExecution is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScriptExecution) String() string {
	var builder strings.Builder
	builder.WriteString("ScriptExecution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("script_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScriptID))
	builder.WriteString(", ")
	builder.WriteString("execution_id=")
	builder.WriteString(_m.ExecutionID)
	builder.WriteString(", ")
	builder.WriteString("executor_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExecutorUserID))
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(_m.TriggerType)
	builder.WriteString(", ")
	builder.WriteString("target_ci_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetCiIds))
	builder.WriteString(", ")
	builder.WriteString("target_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetCount))
	builder.WriteString(", ")
	builder.WriteString("parameters=")
	builder.WriteString(_m.Parameters)
	builder.WriteString(", ")
	builder.WriteString("raw_parameters=")
	builder.WriteString(_m.RawParameters)
	builder.WriteString(", ")
	builder.WriteString("execution_status=")
	builder.WriteString(_m.ExecutionStatus)
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("success_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessCount))
	builder.WriteString(", ")
	builder.WriteString("failure_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailureCount))
	builder.WriteString(", ")
	builder.WriteString("timeout_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutCount))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("execution_log=")
	builder.WriteString(_m.ExecutionLog)
	builder.WriteByte(')')
	return builder.String()
}

// ScriptExecutions is a parsable slice of ScriptExecution.
type ScriptExecutions []*ScriptExecution
