// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/coder-lulu/newbee-ops-rpc/ent/script"
	"github.com/coder-lulu/newbee-ops-rpc/ent/scriptcategory"
)

// ScriptCategoryCreate is the builder for creating a ScriptCategory entity.
type ScriptCategoryCreate struct {
	config
	mutation *ScriptCategoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScriptCategoryCreate) SetCreatedAt(v time.Time) *ScriptCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableCreatedAt(v *time.Time) *ScriptCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScriptCategoryCreate) SetUpdatedAt(v time.Time) *ScriptCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableUpdatedAt(v *time.Time) *ScriptCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ScriptCategoryCreate) SetTenantID(v uint64) *ScriptCategoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableTenantID(v *uint64) *ScriptCategoryCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *ScriptCategoryCreate) SetDepartmentID(v uint64) *ScriptCategoryCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableDepartmentID(v *uint64) *ScriptCategoryCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ScriptCategoryCreate) SetStatus(v uint8) *ScriptCategoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableStatus(v *uint8) *ScriptCategoryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ScriptCategoryCreate) SetName(v string) *ScriptCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *ScriptCategoryCreate) SetCode(v string) *ScriptCategoryCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ScriptCategoryCreate) SetDescription(v string) *ScriptCategoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableDescription(v *string) *ScriptCategoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *ScriptCategoryCreate) SetParentID(v uint64) *ScriptCategoryCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableParentID(v *uint64) *ScriptCategoryCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ScriptCategoryCreate) SetSortOrder(v uint32) *ScriptCategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableSortOrder(v *uint32) *ScriptCategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ScriptCategoryCreate) SetIcon(v string) *ScriptCategoryCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *ScriptCategoryCreate) SetNillableIcon(v *string) *ScriptCategoryCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScriptCategoryCreate) SetID(v uint64) *ScriptCategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParent sets the "parent" edge to the ScriptCategory entity.
func (_c *ScriptCategoryCreate) SetParent(v *ScriptCategory) *ScriptCategoryCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the ScriptCategory entity by IDs.
func (_c *ScriptCategoryCreate) AddChildIDs(ids ...uint64) *ScriptCategoryCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the ScriptCategory entity.
func (_c *ScriptCategoryCreate) AddChildren(v ...*ScriptCategory) *ScriptCategoryCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddScriptIDs adds the "scripts" edge to the Script entity by IDs.
func (_c *ScriptCategoryCreate) AddScriptIDs(ids ...uint64) *ScriptCategoryCreate {
	_c.mutation.AddScriptIDs(ids...)
	return _c
}

// AddScripts adds the "scripts" edges to the Script entity.
func (_c *ScriptCategoryCreate) AddScripts(v ...*Script) *ScriptCategoryCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScriptIDs(ids...)
}

// Mutation returns the ScriptCategoryMutation object of the builder.
func (_c *ScriptCategoryCreate) Mutation() *ScriptCategoryMutation {
	return _c.mutation
}

// Save creates the ScriptCategory in the database.
func (_c *ScriptCategoryCreate) Save(ctx context.Context) (*ScriptCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScriptCategoryCreate) SaveX(ctx context.Context) *ScriptCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScriptCategoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := scriptcategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := scriptcategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := scriptcategory.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := scriptcategory.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := scriptcategory.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScriptCategoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ScriptCategory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ScriptCategory.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ScriptCategory.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ScriptCategory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := scriptcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ScriptCategory.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := scriptcategory.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := scriptcategory.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ScriptCategory.sort_order"`)}
	}
	if v, ok := _c.mutation.Icon(); ok {
		if err := scriptcategory.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "ScriptCategory.icon": %w`, err)}
		}
	}
	return nil
}

func (_c *ScriptCategoryCreate) sqlSave(ctx context.Context) (*ScriptCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScriptCategoryCreate) createSpec() (*ScriptCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &ScriptCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scriptcategory.Table, sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(scriptcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(scriptcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(scriptcategory.FieldTenantID, field.TypeUint64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.DepartmentID(); ok {
		_spec.SetField(scriptcategory.FieldDepartmentID, field.TypeUint64, value)
		_node.DepartmentID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(scriptcategory.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(scriptcategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(scriptcategory.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(scriptcategory.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(scriptcategory.FieldSortOrder, field.TypeUint32, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(scriptcategory.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scriptcategory.ParentTable,
			Columns: []string{scriptcategory.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ChildrenTable,
			Columns: []string{scriptcategory.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scriptcategory.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ScriptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   scriptcategory.ScriptsTable,
			Columns: []string{scriptcategory.ScriptsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(script.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ScriptCategoryCreateBulk is the builder for creating many ScriptCategory entities in bulk.
type ScriptCategoryCreateBulk struct {
	config
	err      error
	builders []*ScriptCategoryCreate
}

// Save creates the ScriptCategory entities in the database.
func (_c *ScriptCategoryCreateBulk) Save(ctx context.Context) ([]*ScriptCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScriptCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScriptCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScriptCategoryCreateBulk) SaveX(ctx context.Context) []*ScriptCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
