// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccessProfilesColumns holds the columns for the "access_profiles" table.
	AccessProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "ci_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "capabilities", Type: field.TypeJSON, Nullable: true},
		{Name: "ports", Type: field.TypeJSON, Nullable: true},
		{Name: "credential_ref", Type: field.TypeString, Nullable: true},
		{Name: "prefer_proxy", Type: field.TypeString, Nullable: true},
		{Name: "jump_chain", Type: field.TypeJSON, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
	}
	// AccessProfilesTable holds the schema information for the "access_profiles" table.
	AccessProfilesTable = &schema.Table{
		Name:       "access_profiles",
		Columns:    AccessProfilesColumns,
		PrimaryKey: []*schema.Column{AccessProfilesColumns[0]},
	}
	// OpsAgentsColumns holds the columns for the "ops_agents" table.
	OpsAgentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "agent_id", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "host", Type: field.TypeString, Size: 255},
		{Name: "port", Type: field.TypeInt, Default: 8080},
		{Name: "api_key", Type: field.TypeString, Size: 255},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "agent_status", Type: field.TypeEnum, Enums: []string{"online", "offline", "error", "maintenance"}, Default: "offline"},
		{Name: "last_heartbeat", Type: field.TypeTime, Nullable: true},
		{Name: "heartbeat_interval", Type: field.TypeInt, Default: 30},
		{Name: "last_online_at", Type: field.TypeTime, Nullable: true},
		{Name: "supported_providers", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "capabilities", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "max_concurrent_tasks", Type: field.TypeInt, Default: 10},
		{Name: "tags", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "region", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "resource_limits", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "local_ip", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "public_ip", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "network_segments", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "active_sessions", Type: field.TypeInt, Default: 0},
		{Name: "cpu_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "memory_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "total_requests", Type: field.TypeInt64, Default: 0},
		{Name: "successful_requests", Type: field.TypeInt64, Default: 0},
		{Name: "failed_requests", Type: field.TypeInt64, Default: 0},
		{Name: "version", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "last_error", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// OpsAgentsTable holds the schema information for the "ops_agents" table.
	OpsAgentsTable = &schema.Table{
		Name:       "ops_agents",
		Columns:    OpsAgentsColumns,
		PrimaryKey: []*schema.Column{OpsAgentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "agent_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentsColumns[3]},
			},
			{
				Name:    "agent_agent_id",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentsColumns[6]},
			},
			{
				Name:    "agent_agent_status",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentsColumns[11]},
			},
			{
				Name:    "agent_last_heartbeat",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentsColumns[12]},
			},
		},
	}
	// OpsAgentGroupsColumns holds the columns for the "ops_agent_groups" table.
	OpsAgentGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "selection_strategy", Type: field.TypeEnum, Enums: []string{"round_robin", "least_loaded", "random", "priority", "geo_nearest"}, Default: "round_robin"},
		{Name: "health_check_interval", Type: field.TypeInt, Default: 60},
		{Name: "auto_failover", Type: field.TypeBool, Default: true},
		{Name: "max_retry_count", Type: field.TypeInt, Default: 3},
	}
	// OpsAgentGroupsTable holds the schema information for the "ops_agent_groups" table.
	OpsAgentGroupsTable = &schema.Table{
		Name:       "ops_agent_groups",
		Columns:    OpsAgentGroupsColumns,
		PrimaryKey: []*schema.Column{OpsAgentGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "agentgroup_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentGroupsColumns[3]},
			},
			{
				Name:    "agentgroup_status",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentGroupsColumns[4]},
			},
		},
	}
	// OpsAgentGroupMembersColumns holds the columns for the "ops_agent_group_members" table.
	OpsAgentGroupMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "priority", Type: field.TypeInt, Default: 100},
		{Name: "weight", Type: field.TypeInt, Default: 1},
		{Name: "joined_at", Type: field.TypeTime, Nullable: true},
		{Name: "agent_id", Type: field.TypeUint64},
		{Name: "agent_group_id", Type: field.TypeUint64},
	}
	// OpsAgentGroupMembersTable holds the schema information for the "ops_agent_group_members" table.
	OpsAgentGroupMembersTable = &schema.Table{
		Name:       "ops_agent_group_members",
		Columns:    OpsAgentGroupMembersColumns,
		PrimaryKey: []*schema.Column{OpsAgentGroupMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ops_agent_group_members_ops_agents_agent",
				Columns:    []*schema.Column{OpsAgentGroupMembersColumns[8]},
				RefColumns: []*schema.Column{OpsAgentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "ops_agent_group_members_ops_agent_groups_agent_group",
				Columns:    []*schema.Column{OpsAgentGroupMembersColumns[9]},
				RefColumns: []*schema.Column{OpsAgentGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "agentgroupmember_agent_id_agent_group_id",
				Unique:  true,
				Columns: []*schema.Column{OpsAgentGroupMembersColumns[8], OpsAgentGroupMembersColumns[9]},
			},
			{
				Name:    "agentgroupmember_agent_group_id",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentGroupMembersColumns[9]},
			},
			{
				Name:    "agentgroupmember_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OpsAgentGroupMembersColumns[3]},
			},
		},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "event_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "type", Type: field.TypeString, Size: 32},
		{Name: "subject_user", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "subject_ci", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "subject_proxy", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "occur_at", Type: field.TypeInt64, Nullable: true},
		{Name: "meta", Type: field.TypeJSON, Nullable: true},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
	}
	// CredentialRefsColumns holds the columns for the "credential_refs" table.
	CredentialRefsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "provider", Type: field.TypeString, Size: 64},
		{Name: "ref", Type: field.TypeString, Size: 256},
		{Name: "scope", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "created_by", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
	}
	// CredentialRefsTable holds the schema information for the "credential_refs" table.
	CredentialRefsTable = &schema.Table{
		Name:       "credential_refs",
		Columns:    CredentialRefsColumns,
		PrimaryKey: []*schema.Column{CredentialRefsColumns[0]},
	}
	// OpsWorkersColumns holds the columns for the "ops_workers" table.
	OpsWorkersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "worker_id", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "ip", Type: field.TypeString, Size: 100},
		{Name: "port", Type: field.TypeInt, Default: 8889},
		{Name: "version", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "region", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "zone", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "capabilities", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "tags", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "endpoints", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "worker_status", Type: field.TypeEnum, Enums: []string{"online", "degraded", "offline"}, Default: "offline"},
		{Name: "last_heartbeat", Type: field.TypeTime, Nullable: true},
		{Name: "register_time", Type: field.TypeTime, Nullable: true},
		{Name: "weight", Type: field.TypeInt, Default: 100},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "cpu_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "memory_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "disk_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "network_in", Type: field.TypeUint64, Default: 0},
		{Name: "network_out", Type: field.TypeUint64, Default: 0},
		{Name: "active_sessions", Type: field.TypeInt, Default: 0},
		{Name: "total_requests", Type: field.TypeUint64, Default: 0},
		{Name: "success_count", Type: field.TypeUint64, Default: 0},
		{Name: "failure_count", Type: field.TypeUint64, Default: 0},
		{Name: "max_sessions", Type: field.TypeInt, Default: 1000},
		{Name: "health_check_failures", Type: field.TypeInt, Default: 0},
		{Name: "last_health_check", Type: field.TypeTime, Nullable: true},
		{Name: "health_check_url", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "local_ip", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "public_ip", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "network_segments", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"mysql": "json"}},
		{Name: "last_error", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// OpsWorkersTable holds the schema information for the "ops_workers" table.
	OpsWorkersTable = &schema.Table{
		Name:       "ops_workers",
		Columns:    OpsWorkersColumns,
		PrimaryKey: []*schema.Column{OpsWorkersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "proxy_tenant_id_worker_status_status",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkersColumns[3], OpsWorkersColumns[15], OpsWorkersColumns[4]},
			},
			{
				Name:    "proxy_tenant_id_region_worker_status",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkersColumns[3], OpsWorkersColumns[10], OpsWorkersColumns[15]},
			},
			{
				Name:    "proxy_worker_id",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkersColumns[5]},
			},
			{
				Name:    "proxy_last_heartbeat",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkersColumns[16]},
			},
			{
				Name:    "proxy_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkersColumns[3]},
			},
		},
	}
	// OpsWorkerGroupsColumns holds the columns for the "ops_worker_groups" table.
	OpsWorkerGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "department_id", Type: field.TypeUint64, Nullable: true},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "selection_strategy", Type: field.TypeEnum, Enums: []string{"round_robin", "least_connections", "weighted", "random", "consistent_hash"}, Default: "least_connections"},
		{Name: "health_check_interval", Type: field.TypeInt, Default: 60},
		{Name: "auto_failover", Type: field.TypeBool, Default: true},
		{Name: "max_retry_count", Type: field.TypeInt, Default: 3},
		{Name: "min_healthy_workers", Type: field.TypeInt, Default: 1},
		{Name: "connection_timeout", Type: field.TypeInt, Default: 30},
		{Name: "request_timeout", Type: field.TypeInt, Default: 60},
		{Name: "total_members", Type: field.TypeInt, Default: 0},
		{Name: "online_members", Type: field.TypeInt, Default: 0},
		{Name: "total_weight", Type: field.TypeInt, Default: 0},
	}
	// OpsWorkerGroupsTable holds the schema information for the "ops_worker_groups" table.
	OpsWorkerGroupsTable = &schema.Table{
		Name:       "ops_worker_groups",
		Columns:    OpsWorkerGroupsColumns,
		PrimaryKey: []*schema.Column{OpsWorkerGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "proxygroup_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupsColumns[3], OpsWorkerGroupsColumns[5]},
			},
			{
				Name:    "proxygroup_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupsColumns[3]},
			},
			{
				Name:    "proxygroup_name",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupsColumns[6]},
			},
			{
				Name:    "proxygroup_status",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupsColumns[5]},
			},
		},
	}
	// OpsWorkerGroupMembersColumns holds the columns for the "ops_worker_group_members" table.
	OpsWorkerGroupMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "department_id", Type: field.TypeUint64, Nullable: true},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "weight", Type: field.TypeInt, Default: 100},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "joined_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_selected_at", Type: field.TypeTime, Nullable: true},
		{Name: "select_count", Type: field.TypeInt, Default: 0},
		{Name: "is_backup", Type: field.TypeBool, Default: false},
		{Name: "consecutive_failures", Type: field.TypeInt, Default: 0},
		{Name: "last_failure_at", Type: field.TypeTime, Nullable: true},
		{Name: "worker_id", Type: field.TypeUint64},
		{Name: "worker_group_id", Type: field.TypeUint64},
	}
	// OpsWorkerGroupMembersTable holds the schema information for the "ops_worker_group_members" table.
	OpsWorkerGroupMembersTable = &schema.Table{
		Name:       "ops_worker_group_members",
		Columns:    OpsWorkerGroupMembersColumns,
		PrimaryKey: []*schema.Column{OpsWorkerGroupMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ops_worker_group_members_ops_workers_proxy",
				Columns:    []*schema.Column{OpsWorkerGroupMembersColumns[14]},
				RefColumns: []*schema.Column{OpsWorkersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "ops_worker_group_members_ops_worker_groups_proxy_group",
				Columns:    []*schema.Column{OpsWorkerGroupMembersColumns[15]},
				RefColumns: []*schema.Column{OpsWorkerGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "proxygroupmember_worker_id_worker_group_id",
				Unique:  true,
				Columns: []*schema.Column{OpsWorkerGroupMembersColumns[14], OpsWorkerGroupMembersColumns[15]},
			},
			{
				Name:    "proxygroupmember_worker_group_id_priority_weight",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupMembersColumns[15], OpsWorkerGroupMembersColumns[7], OpsWorkerGroupMembersColumns[6]},
			},
			{
				Name:    "proxygroupmember_worker_id",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupMembersColumns[14]},
			},
			{
				Name:    "proxygroupmember_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupMembersColumns[3]},
			},
			{
				Name:    "proxygroupmember_status",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerGroupMembersColumns[5]},
			},
		},
	}
	// OpsWorkerMetricsColumns holds the columns for the "ops_worker_metrics" table.
	OpsWorkerMetricsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "worker_id", Type: field.TypeString, Size: 100},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "cpu_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "memory_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "disk_usage", Type: field.TypeFloat64, Default: 0},
		{Name: "network_in_delta", Type: field.TypeUint64, Default: 0},
		{Name: "network_out_delta", Type: field.TypeUint64, Default: 0},
		{Name: "active_sessions", Type: field.TypeInt, Default: 0},
		{Name: "request_count_delta", Type: field.TypeUint64, Default: 0},
		{Name: "success_count_delta", Type: field.TypeUint64, Default: 0},
		{Name: "failure_count_delta", Type: field.TypeUint64, Default: 0},
		{Name: "avg_latency_ms", Type: field.TypeFloat64, Default: 0},
		{Name: "worker_status", Type: field.TypeString, Default: "offline"},
	}
	// OpsWorkerMetricsTable holds the schema information for the "ops_worker_metrics" table.
	OpsWorkerMetricsTable = &schema.Table{
		Name:       "ops_worker_metrics",
		Columns:    OpsWorkerMetricsColumns,
		PrimaryKey: []*schema.Column{OpsWorkerMetricsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "proxymetrics_worker_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerMetricsColumns[4], OpsWorkerMetricsColumns[5]},
			},
			{
				Name:    "proxymetrics_tenant_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerMetricsColumns[3], OpsWorkerMetricsColumns[5]},
			},
			{
				Name:    "proxymetrics_timestamp",
				Unique:  false,
				Columns: []*schema.Column{OpsWorkerMetricsColumns[5]},
			},
		},
	}
	// OpsScriptsColumns holds the columns for the "ops_scripts" table.
	OpsScriptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "department_id", Type: field.TypeUint64, Nullable: true},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "code", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "script_type", Type: field.TypeString, Size: 50},
		{Name: "executor", Type: field.TypeString, Size: 50},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "is_template", Type: field.TypeBool, Default: false},
		{Name: "template_engine", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "parameters", Type: field.TypeJSON, Nullable: true},
		{Name: "version", Type: field.TypeString, Size: 50, Default: "1.0.0"},
		{Name: "base_version_id", Type: field.TypeUint64, Nullable: true},
		{Name: "is_latest", Type: field.TypeBool, Default: true},
		{Name: "target_ci_types", Type: field.TypeJSON, Nullable: true},
		{Name: "target_os_types", Type: field.TypeJSON, Nullable: true},
		{Name: "target_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "credential_ref", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "required_capabilities", Type: field.TypeJSON, Nullable: true},
		{Name: "default_timeout", Type: field.TypeUint32, Default: 300},
		{Name: "default_workdir", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "default_env", Type: field.TypeJSON, Nullable: true},
		{Name: "require_confirmation", Type: field.TypeBool, Default: false},
		{Name: "risk_level", Type: field.TypeString, Size: 20, Default: "low"},
		{Name: "schedulable", Type: field.TypeBool, Default: true},
		{Name: "default_schedule", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "execution_count", Type: field.TypeUint64, Default: 0},
		{Name: "success_count", Type: field.TypeUint64, Default: 0},
		{Name: "failure_count", Type: field.TypeUint64, Default: 0},
		{Name: "last_executed_at", Type: field.TypeInt64, Nullable: true},
		{Name: "category_id", Type: field.TypeUint64, Nullable: true},
	}
	// OpsScriptsTable holds the schema information for the "ops_scripts" table.
	OpsScriptsTable = &schema.Table{
		Name:       "ops_scripts",
		Columns:    OpsScriptsColumns,
		PrimaryKey: []*schema.Column{OpsScriptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ops_scripts_ops_script_categories_scripts",
				Columns:    []*schema.Column{OpsScriptsColumns[35]},
				RefColumns: []*schema.Column{OpsScriptCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "script_tenant_id_code",
				Unique:  true,
				Columns: []*schema.Column{OpsScriptsColumns[3], OpsScriptsColumns[7]},
			},
			{
				Name:    "script_tenant_id_category_id",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptsColumns[3], OpsScriptsColumns[35]},
			},
			{
				Name:    "script_script_type",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptsColumns[10]},
			},
			{
				Name:    "script_is_latest",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptsColumns[18]},
			},
		},
	}
	// OpsScriptCategoriesColumns holds the columns for the "ops_script_categories" table.
	OpsScriptCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "department_id", Type: field.TypeUint64, Nullable: true},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "code", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "sort_order", Type: field.TypeUint32, Default: 0},
		{Name: "icon", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "parent_id", Type: field.TypeUint64, Nullable: true},
	}
	// OpsScriptCategoriesTable holds the schema information for the "ops_script_categories" table.
	OpsScriptCategoriesTable = &schema.Table{
		Name:       "ops_script_categories",
		Columns:    OpsScriptCategoriesColumns,
		PrimaryKey: []*schema.Column{OpsScriptCategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ops_script_categories_ops_script_categories_children",
				Columns:    []*schema.Column{OpsScriptCategoriesColumns[11]},
				RefColumns: []*schema.Column{OpsScriptCategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "scriptcategory_tenant_id_code",
				Unique:  true,
				Columns: []*schema.Column{OpsScriptCategoriesColumns[3], OpsScriptCategoriesColumns[7]},
			},
			{
				Name:    "scriptcategory_tenant_id_parent_id",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptCategoriesColumns[3], OpsScriptCategoriesColumns[11]},
			},
			{
				Name:    "scriptcategory_sort_order",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptCategoriesColumns[9]},
			},
		},
	}
	// OpsScriptExecutionsColumns holds the columns for the "ops_script_executions" table.
	OpsScriptExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "execution_id", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "executor_user_id", Type: field.TypeUint64, Nullable: true},
		{Name: "trigger_type", Type: field.TypeString, Size: 20, Default: "manual"},
		{Name: "target_ci_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "target_count", Type: field.TypeUint32, Default: 0},
		{Name: "parameters", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "raw_parameters", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "execution_status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "duration_ms", Type: field.TypeUint64, Default: 0},
		{Name: "success_count", Type: field.TypeUint32, Default: 0},
		{Name: "failure_count", Type: field.TypeUint32, Default: 0},
		{Name: "timeout_count", Type: field.TypeUint32, Default: 0},
		{Name: "task_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "execution_log", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "script_id", Type: field.TypeUint64},
	}
	// OpsScriptExecutionsTable holds the schema information for the "ops_script_executions" table.
	OpsScriptExecutionsTable = &schema.Table{
		Name:       "ops_script_executions",
		Columns:    OpsScriptExecutionsColumns,
		PrimaryKey: []*schema.Column{OpsScriptExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ops_script_executions_ops_scripts_executions",
				Columns:    []*schema.Column{OpsScriptExecutionsColumns[22]},
				RefColumns: []*schema.Column{OpsScriptsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "scriptexecution_tenant_id_execution_id",
				Unique:  true,
				Columns: []*schema.Column{OpsScriptExecutionsColumns[3], OpsScriptExecutionsColumns[5]},
			},
			{
				Name:    "scriptexecution_script_id_started_at",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionsColumns[22], OpsScriptExecutionsColumns[13]},
			},
			{
				Name:    "scriptexecution_execution_status",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionsColumns[12]},
			},
			{
				Name:    "scriptexecution_tenant_id_execution_status",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionsColumns[3], OpsScriptExecutionsColumns[12]},
			},
		},
	}
	// OpsScriptExecutionDetailsColumns holds the columns for the "ops_script_execution_details" table.
	OpsScriptExecutionDetailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "ci_id", Type: field.TypeString, Size: 64},
		{Name: "ci_name", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "ci_ip", Type: field.TypeString, Nullable: true, Size: 50},
		{Name: "exec_status", Type: field.TypeString, Size: 20, Default: "pending"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "duration_ms", Type: field.TypeUint64, Default: 0},
		{Name: "output", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "error_output", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "exit_code", Type: field.TypeInt, Nullable: true},
		{Name: "full_output_path", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "task_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "worker_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "proxy_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "retry_count", Type: field.TypeUint32, Default: 0},
		{Name: "execution_id", Type: field.TypeUint64},
	}
	// OpsScriptExecutionDetailsTable holds the schema information for the "ops_script_execution_details" table.
	OpsScriptExecutionDetailsTable = &schema.Table{
		Name:       "ops_script_execution_details",
		Columns:    OpsScriptExecutionDetailsColumns,
		PrimaryKey: []*schema.Column{OpsScriptExecutionDetailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ops_script_execution_details_ops_script_executions_details",
				Columns:    []*schema.Column{OpsScriptExecutionDetailsColumns[21]},
				RefColumns: []*schema.Column{OpsScriptExecutionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "scriptexecutiondetail_execution_id",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionDetailsColumns[21]},
			},
			{
				Name:    "scriptexecutiondetail_tenant_id_execution_id",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionDetailsColumns[3], OpsScriptExecutionDetailsColumns[21]},
			},
			{
				Name:    "scriptexecutiondetail_ci_id",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionDetailsColumns[5]},
			},
			{
				Name:    "scriptexecutiondetail_exec_status",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionDetailsColumns[8]},
			},
			{
				Name:    "scriptexecutiondetail_task_id",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptExecutionDetailsColumns[16]},
			},
		},
	}
	// OpsScriptVersionsColumns holds the columns for the "ops_script_versions" table.
	OpsScriptVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "version", Type: field.TypeString, Size: 50},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "parameters", Type: field.TypeJSON, Nullable: true},
		{Name: "script_type", Type: field.TypeString, Size: 50},
		{Name: "executor", Type: field.TypeString, Size: 50},
		{Name: "change_log", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_by", Type: field.TypeUint64},
		{Name: "checksum", Type: field.TypeString, Size: 64},
		{Name: "script_id", Type: field.TypeUint64},
	}
	// OpsScriptVersionsTable holds the schema information for the "ops_script_versions" table.
	OpsScriptVersionsTable = &schema.Table{
		Name:       "ops_script_versions",
		Columns:    OpsScriptVersionsColumns,
		PrimaryKey: []*schema.Column{OpsScriptVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ops_script_versions_ops_scripts_versions",
				Columns:    []*schema.Column{OpsScriptVersionsColumns[12]},
				RefColumns: []*schema.Column{OpsScriptsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "scriptversion_script_id_version",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptVersionsColumns[12], OpsScriptVersionsColumns[4]},
			},
			{
				Name:    "scriptversion_tenant_id_script_id",
				Unique:  false,
				Columns: []*schema.Column{OpsScriptVersionsColumns[3], OpsScriptVersionsColumns[12]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "session_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "user_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "ci_id", Type: field.TypeString, Size: 128},
		{Name: "protocol", Type: field.TypeString, Size: 16},
		{Name: "proxy_id", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "endpoint", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "worker_id", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "worker_ip", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "worker_port", Type: field.TypeInt, Nullable: true},
		{Name: "status_str", Type: field.TypeString, Size: 16, Default: "active"},
		{Name: "expires_at", Type: field.TypeInt64, Nullable: true},
		{Name: "closed_at", Type: field.TypeInt64, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
	}
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Default: 1},
		{Name: "tenant_id", Type: field.TypeUint64, Default: 1},
		{Name: "task_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "creator_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "ci_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "executor", Type: field.TypeString, Size: 16, Default: "agent"},
		{Name: "worker_id", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "command_content", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "command_timeout", Type: field.TypeInt, Nullable: true},
		{Name: "command_workdir", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "command_env", Type: field.TypeJSON, Nullable: true},
		{Name: "status_str", Type: field.TypeString, Size: 16, Default: "pending"},
		{Name: "result_output", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "result_data", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "error_msg", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "exit_code", Type: field.TypeInt, Nullable: true},
		{Name: "remote_task_id", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "start_time", Type: field.TypeInt64, Nullable: true},
		{Name: "end_time", Type: field.TypeInt64, Nullable: true},
		{Name: "dispatched_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "execution_time_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccessProfilesTable,
		OpsAgentsTable,
		OpsAgentGroupsTable,
		OpsAgentGroupMembersTable,
		AuditEventsTable,
		CredentialRefsTable,
		OpsWorkersTable,
		OpsWorkerGroupsTable,
		OpsWorkerGroupMembersTable,
		OpsWorkerMetricsTable,
		OpsScriptsTable,
		OpsScriptCategoriesTable,
		OpsScriptExecutionsTable,
		OpsScriptExecutionDetailsTable,
		OpsScriptVersionsTable,
		SessionsTable,
		TasksTable,
	}
)

func init() {
	OpsAgentsTable.Annotation = &entsql.Annotation{
		Table: "ops_agents",
	}
	OpsAgentGroupsTable.Annotation = &entsql.Annotation{
		Table: "ops_agent_groups",
	}
	OpsAgentGroupMembersTable.ForeignKeys[0].RefTable = OpsAgentsTable
	OpsAgentGroupMembersTable.ForeignKeys[1].RefTable = OpsAgentGroupsTable
	OpsAgentGroupMembersTable.Annotation = &entsql.Annotation{
		Table: "ops_agent_group_members",
	}
	OpsWorkersTable.Annotation = &entsql.Annotation{
		Table: "ops_workers",
	}
	OpsWorkerGroupsTable.Annotation = &entsql.Annotation{
		Table: "ops_worker_groups",
	}
	OpsWorkerGroupMembersTable.ForeignKeys[0].RefTable = OpsWorkersTable
	OpsWorkerGroupMembersTable.ForeignKeys[1].RefTable = OpsWorkerGroupsTable
	OpsWorkerGroupMembersTable.Annotation = &entsql.Annotation{
		Table: "ops_worker_group_members",
	}
	OpsWorkerMetricsTable.Annotation = &entsql.Annotation{
		Table: "ops_worker_metrics",
	}
	OpsScriptsTable.ForeignKeys[0].RefTable = OpsScriptCategoriesTable
	OpsScriptsTable.Annotation = &entsql.Annotation{
		Table: "ops_scripts",
	}
	OpsScriptCategoriesTable.ForeignKeys[0].RefTable = OpsScriptCategoriesTable
	OpsScriptCategoriesTable.Annotation = &entsql.Annotation{
		Table: "ops_script_categories",
	}
	OpsScriptExecutionsTable.ForeignKeys[0].RefTable = OpsScriptsTable
	OpsScriptExecutionsTable.Annotation = &entsql.Annotation{
		Table:     "ops_script_executions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_unicode_ci",
	}
	OpsScriptExecutionDetailsTable.ForeignKeys[0].RefTable = OpsScriptExecutionsTable
	OpsScriptExecutionDetailsTable.Annotation = &entsql.Annotation{
		Table:     "ops_script_execution_details",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_unicode_ci",
	}
	OpsScriptVersionsTable.ForeignKeys[0].RefTable = OpsScriptsTable
	OpsScriptVersionsTable.Annotation = &entsql.Annotation{
		Table: "ops_script_versions",
	}
}
