// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: desc/ops.proto

package newbee_ops_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewbeeOpsRpc_CreateAccessProfile_FullMethodName   = "/newbee_ops_rpc.NewbeeOpsRpc/createAccessProfile"
	NewbeeOpsRpc_UpdateAccessProfile_FullMethodName   = "/newbee_ops_rpc.NewbeeOpsRpc/updateAccessProfile"
	NewbeeOpsRpc_GetAccessProfileList_FullMethodName  = "/newbee_ops_rpc.NewbeeOpsRpc/getAccessProfileList"
	NewbeeOpsRpc_GetAccessProfileById_FullMethodName  = "/newbee_ops_rpc.NewbeeOpsRpc/getAccessProfileById"
	NewbeeOpsRpc_DeleteAccessProfile_FullMethodName   = "/newbee_ops_rpc.NewbeeOpsRpc/deleteAccessProfile"
	NewbeeOpsRpc_CreateTask_FullMethodName            = "/newbee_ops_rpc.NewbeeOpsRpc/createTask"
	NewbeeOpsRpc_UpdateTask_FullMethodName            = "/newbee_ops_rpc.NewbeeOpsRpc/updateTask"
	NewbeeOpsRpc_GetTaskList_FullMethodName           = "/newbee_ops_rpc.NewbeeOpsRpc/getTaskList"
	NewbeeOpsRpc_GetTaskById_FullMethodName           = "/newbee_ops_rpc.NewbeeOpsRpc/getTaskById"
	NewbeeOpsRpc_DeleteTask_FullMethodName            = "/newbee_ops_rpc.NewbeeOpsRpc/deleteTask"
	NewbeeOpsRpc_GetTaskByTaskId_FullMethodName       = "/newbee_ops_rpc.NewbeeOpsRpc/getTaskByTaskId"
	NewbeeOpsRpc_CreateSession_FullMethodName         = "/newbee_ops_rpc.NewbeeOpsRpc/createSession"
	NewbeeOpsRpc_UpdateSession_FullMethodName         = "/newbee_ops_rpc.NewbeeOpsRpc/updateSession"
	NewbeeOpsRpc_GetSessionList_FullMethodName        = "/newbee_ops_rpc.NewbeeOpsRpc/getSessionList"
	NewbeeOpsRpc_GetSessionById_FullMethodName        = "/newbee_ops_rpc.NewbeeOpsRpc/getSessionById"
	NewbeeOpsRpc_GetSessionBySessionId_FullMethodName = "/newbee_ops_rpc.NewbeeOpsRpc/getSessionBySessionId"
	NewbeeOpsRpc_DeleteSession_FullMethodName         = "/newbee_ops_rpc.NewbeeOpsRpc/deleteSession"
)

// NewbeeOpsRpcClient is the client API for NewbeeOpsRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewbeeOpsRpcClient interface {
	// AccessProfile management
	// group: access_profile
	CreateAccessProfile(ctx context.Context, in *AccessProfileInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
	// group: access_profile
	UpdateAccessProfile(ctx context.Context, in *AccessProfileInfo, opts ...grpc.CallOption) (*BaseResp, error)
	// group: access_profile
	GetAccessProfileList(ctx context.Context, in *AccessProfileListReq, opts ...grpc.CallOption) (*AccessProfileListResp, error)
	// group: access_profile
	GetAccessProfileById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*AccessProfileInfo, error)
	// group: access_profile
	DeleteAccessProfile(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	// group: task
	CreateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
	// group: task
	UpdateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseResp, error)
	// group: task
	GetTaskList(ctx context.Context, in *TaskListReq, opts ...grpc.CallOption) (*TaskListResp, error)
	// group: task
	GetTaskById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*TaskInfo, error)
	// group: task
	DeleteTask(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	// group: task
	GetTaskByTaskId(ctx context.Context, in *TaskIdReq, opts ...grpc.CallOption) (*TaskInfo, error)
	// group: session
	CreateSession(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
	// group: session
	UpdateSession(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*BaseResp, error)
	// group: session
	GetSessionList(ctx context.Context, in *SessionListReq, opts ...grpc.CallOption) (*SessionListResp, error)
	// group: session
	GetSessionById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*SessionInfo, error)
	// group: session
	GetSessionBySessionId(ctx context.Context, in *SessionSIDReq, opts ...grpc.CallOption) (*SessionInfo, error)
	// group: session
	DeleteSession(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error)
}

type newbeeOpsRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewNewbeeOpsRpcClient(cc grpc.ClientConnInterface) NewbeeOpsRpcClient {
	return &newbeeOpsRpcClient{cc}
}

func (c *newbeeOpsRpcClient) CreateAccessProfile(ctx context.Context, in *AccessProfileInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseIDResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_CreateAccessProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) UpdateAccessProfile(ctx context.Context, in *AccessProfileInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_UpdateAccessProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetAccessProfileList(ctx context.Context, in *AccessProfileListReq, opts ...grpc.CallOption) (*AccessProfileListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessProfileListResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetAccessProfileList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetAccessProfileById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*AccessProfileInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessProfileInfo)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetAccessProfileById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) DeleteAccessProfile(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_DeleteAccessProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) CreateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseIDResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) UpdateTask(ctx context.Context, in *TaskInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetTaskList(ctx context.Context, in *TaskListReq, opts ...grpc.CallOption) (*TaskListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskListResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetTaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetTaskById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*TaskInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskInfo)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetTaskById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) DeleteTask(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetTaskByTaskId(ctx context.Context, in *TaskIdReq, opts ...grpc.CallOption) (*TaskInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskInfo)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetTaskByTaskId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) CreateSession(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseIDResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) UpdateSession(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetSessionList(ctx context.Context, in *SessionListReq, opts ...grpc.CallOption) (*SessionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionListResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetSessionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetSessionById(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetSessionById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) GetSessionBySessionId(ctx context.Context, in *SessionSIDReq, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_GetSessionBySessionId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newbeeOpsRpcClient) DeleteSession(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, NewbeeOpsRpc_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewbeeOpsRpcServer is the server API for NewbeeOpsRpc service.
// All implementations must embed UnimplementedNewbeeOpsRpcServer
// for forward compatibility.
type NewbeeOpsRpcServer interface {
	// AccessProfile management
	// group: access_profile
	CreateAccessProfile(context.Context, *AccessProfileInfo) (*BaseIDResp, error)
	// group: access_profile
	UpdateAccessProfile(context.Context, *AccessProfileInfo) (*BaseResp, error)
	// group: access_profile
	GetAccessProfileList(context.Context, *AccessProfileListReq) (*AccessProfileListResp, error)
	// group: access_profile
	GetAccessProfileById(context.Context, *IDReq) (*AccessProfileInfo, error)
	// group: access_profile
	DeleteAccessProfile(context.Context, *IDsReq) (*BaseResp, error)
	// group: task
	CreateTask(context.Context, *TaskInfo) (*BaseIDResp, error)
	// group: task
	UpdateTask(context.Context, *TaskInfo) (*BaseResp, error)
	// group: task
	GetTaskList(context.Context, *TaskListReq) (*TaskListResp, error)
	// group: task
	GetTaskById(context.Context, *IDReq) (*TaskInfo, error)
	// group: task
	DeleteTask(context.Context, *IDsReq) (*BaseResp, error)
	// group: task
	GetTaskByTaskId(context.Context, *TaskIdReq) (*TaskInfo, error)
	// group: session
	CreateSession(context.Context, *SessionInfo) (*BaseIDResp, error)
	// group: session
	UpdateSession(context.Context, *SessionInfo) (*BaseResp, error)
	// group: session
	GetSessionList(context.Context, *SessionListReq) (*SessionListResp, error)
	// group: session
	GetSessionById(context.Context, *IDReq) (*SessionInfo, error)
	// group: session
	GetSessionBySessionId(context.Context, *SessionSIDReq) (*SessionInfo, error)
	// group: session
	DeleteSession(context.Context, *IDsReq) (*BaseResp, error)
	mustEmbedUnimplementedNewbeeOpsRpcServer()
}

// UnimplementedNewbeeOpsRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewbeeOpsRpcServer struct{}

func (UnimplementedNewbeeOpsRpcServer) CreateAccessProfile(context.Context, *AccessProfileInfo) (*BaseIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccessProfile not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) UpdateAccessProfile(context.Context, *AccessProfileInfo) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccessProfile not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetAccessProfileList(context.Context, *AccessProfileListReq) (*AccessProfileListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessProfileList not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetAccessProfileById(context.Context, *IDReq) (*AccessProfileInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessProfileById not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) DeleteAccessProfile(context.Context, *IDsReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccessProfile not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) CreateTask(context.Context, *TaskInfo) (*BaseIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) UpdateTask(context.Context, *TaskInfo) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetTaskList(context.Context, *TaskListReq) (*TaskListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskList not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetTaskById(context.Context, *IDReq) (*TaskInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskById not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) DeleteTask(context.Context, *IDsReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetTaskByTaskId(context.Context, *TaskIdReq) (*TaskInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskByTaskId not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) CreateSession(context.Context, *SessionInfo) (*BaseIDResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) UpdateSession(context.Context, *SessionInfo) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetSessionList(context.Context, *SessionListReq) (*SessionListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionList not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetSessionById(context.Context, *IDReq) (*SessionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionById not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) GetSessionBySessionId(context.Context, *SessionSIDReq) (*SessionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionBySessionId not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) DeleteSession(context.Context, *IDsReq) (*BaseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedNewbeeOpsRpcServer) mustEmbedUnimplementedNewbeeOpsRpcServer() {}
func (UnimplementedNewbeeOpsRpcServer) testEmbeddedByValue()                      {}

// UnsafeNewbeeOpsRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewbeeOpsRpcServer will
// result in compilation errors.
type UnsafeNewbeeOpsRpcServer interface {
	mustEmbedUnimplementedNewbeeOpsRpcServer()
}

func RegisterNewbeeOpsRpcServer(s grpc.ServiceRegistrar, srv NewbeeOpsRpcServer) {
	// If the following call pancis, it indicates UnimplementedNewbeeOpsRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewbeeOpsRpc_ServiceDesc, srv)
}

func _NewbeeOpsRpc_CreateAccessProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessProfileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).CreateAccessProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_CreateAccessProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).CreateAccessProfile(ctx, req.(*AccessProfileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_UpdateAccessProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessProfileInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).UpdateAccessProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_UpdateAccessProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).UpdateAccessProfile(ctx, req.(*AccessProfileInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetAccessProfileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessProfileListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetAccessProfileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetAccessProfileList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetAccessProfileList(ctx, req.(*AccessProfileListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetAccessProfileById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetAccessProfileById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetAccessProfileById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetAccessProfileById(ctx, req.(*IDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_DeleteAccessProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).DeleteAccessProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_DeleteAccessProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).DeleteAccessProfile(ctx, req.(*IDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).CreateTask(ctx, req.(*TaskInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).UpdateTask(ctx, req.(*TaskInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetTaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetTaskList(ctx, req.(*TaskListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetTaskById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetTaskById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetTaskById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetTaskById(ctx, req.(*IDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).DeleteTask(ctx, req.(*IDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetTaskByTaskId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetTaskByTaskId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetTaskByTaskId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetTaskByTaskId(ctx, req.(*TaskIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).CreateSession(ctx, req.(*SessionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).UpdateSession(ctx, req.(*SessionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetSessionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetSessionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetSessionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetSessionList(ctx, req.(*SessionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetSessionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetSessionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetSessionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetSessionById(ctx, req.(*IDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_GetSessionBySessionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionSIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).GetSessionBySessionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_GetSessionBySessionId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).GetSessionBySessionId(ctx, req.(*SessionSIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewbeeOpsRpc_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewbeeOpsRpcServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewbeeOpsRpc_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewbeeOpsRpcServer).DeleteSession(ctx, req.(*IDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NewbeeOpsRpc_ServiceDesc is the grpc.ServiceDesc for NewbeeOpsRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewbeeOpsRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "newbee_ops_rpc.NewbeeOpsRpc",
	HandlerType: (*NewbeeOpsRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createAccessProfile",
			Handler:    _NewbeeOpsRpc_CreateAccessProfile_Handler,
		},
		{
			MethodName: "updateAccessProfile",
			Handler:    _NewbeeOpsRpc_UpdateAccessProfile_Handler,
		},
		{
			MethodName: "getAccessProfileList",
			Handler:    _NewbeeOpsRpc_GetAccessProfileList_Handler,
		},
		{
			MethodName: "getAccessProfileById",
			Handler:    _NewbeeOpsRpc_GetAccessProfileById_Handler,
		},
		{
			MethodName: "deleteAccessProfile",
			Handler:    _NewbeeOpsRpc_DeleteAccessProfile_Handler,
		},
		{
			MethodName: "createTask",
			Handler:    _NewbeeOpsRpc_CreateTask_Handler,
		},
		{
			MethodName: "updateTask",
			Handler:    _NewbeeOpsRpc_UpdateTask_Handler,
		},
		{
			MethodName: "getTaskList",
			Handler:    _NewbeeOpsRpc_GetTaskList_Handler,
		},
		{
			MethodName: "getTaskById",
			Handler:    _NewbeeOpsRpc_GetTaskById_Handler,
		},
		{
			MethodName: "deleteTask",
			Handler:    _NewbeeOpsRpc_DeleteTask_Handler,
		},
		{
			MethodName: "getTaskByTaskId",
			Handler:    _NewbeeOpsRpc_GetTaskByTaskId_Handler,
		},
		{
			MethodName: "createSession",
			Handler:    _NewbeeOpsRpc_CreateSession_Handler,
		},
		{
			MethodName: "updateSession",
			Handler:    _NewbeeOpsRpc_UpdateSession_Handler,
		},
		{
			MethodName: "getSessionList",
			Handler:    _NewbeeOpsRpc_GetSessionList_Handler,
		},
		{
			MethodName: "getSessionById",
			Handler:    _NewbeeOpsRpc_GetSessionById_Handler,
		},
		{
			MethodName: "getSessionBySessionId",
			Handler:    _NewbeeOpsRpc_GetSessionBySessionId_Handler,
		},
		{
			MethodName: "deleteSession",
			Handler:    _NewbeeOpsRpc_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desc/ops.proto",
}
